
--1- Crie um script para criar as 4 tabelas abaixo:
CREATE TABLE SAMSUNG(
ID_SAMSUNG INT IDENTITY PRIMARY KEY,
PRODUTO VARCHAR (800) NOT NULL,
PRECO DECIMAL (18,2), 
DATA_LANCAMENTO DATE)
 

CREATE TABLE MOTOROLA(
ID_SMARTPHONE INT IDENTITY PRIMARY KEY,
NOME_PRODUTO VARCHAR (600) NOT NULL,
VALOR_PRODUTO DECIMAL (18,2),
DATA DATE)
 
CREATE TABLE LG(
ID_LG_SMARTPHONE INT IDENTITY PRIMARY KEY,
NOME_APARELHO VARCHAR (900) NOT NULL,
VALOR_COMERCIAL DECIMAL (18,2),
DATA_DISPONIBILIDADE DATE)
 

CREATE TABLE SMARTPHONE(
ID_SMART INT IDENTITY PRIMARY KEY,
ID_TABELA_ORIGEM INT NOT NULL,
NOME_SMARTPHONE VARCHAR (900) NOT NULL,
PRECO_TABELA DECIMAL(18,2) NOT NULL,
MARCA VARCHAR (200) NOT NULL,
DATA_CADASTRO DATETIME NOT NULL,
LOGIN_USUARIO VARCHAR(500) NOT NULL
)



--2-Crie um script, utilizando o comando insert, para inserir os seguintes valores nas colunas das tabelas abaixo:
INSERT INTO SAMSUNG 
(PRODUTO,PRECO,DATA_LANCAMENTO)
VALUES
('Smartphone Samsung Galaxy A51', 2000.00,'20190809'),
('Smartphone Samsung Galaxy A20', 1100.00,'20190409'),
('Smartphone Samsung Galaxy A10', 800.00 ,'20180409')
 
INSERT INTO MOTOROLA
(NOME_PRODUTO, VALOR_PRODUTO, DATA)
VALUES
('Smartphone Motorola One Macro', 800.00, '20180808'),
('Smartphone Moto G8', 1300.00,'20180808'),
('Smartphone Motorola Moto E6', 1200.00, '20180808'),
('Smartphone Motorola Moto E6 PLUS', 1400.00,NULL)

 
INSERT INTO LG
(NOME_APARELHO,VALOR_COMERCIAL,DATA_DISPONIBILIDADE)
VALUES
('Smartphone LG K50S Preto',900.00,'20190809'),
('Smartphone LG K12', 1800.00, NULL),
('Smartphone LG K51S', 1300.00, '20180808')



/*3-A tabela SMARTPHONES foi criada para integrar os dados de smartphones dos fornecedores SAMSUNG, MOTOROLA e LG. 
Crie um script para podermos inserir os dados das tabelas SAMSUNG, MOTOROLA E LG na tabela SMARTPHONES.*/


INSERT INTO SMARTPHONE
(ID_TABELA_ORIGEM,NOME_SMARTPHONE,PRECO_TABELA,MARCA,DATA_CADASTRO,LOGIN_USUARIO)
SELECT ID_SAMSUNG, PRODUTO, PRECO,'SAMSUNG',GETDATE(), SYSTEM_USER FROM SAMSUNG

INSERT INTO SMARTPHONE
(ID_TABELA_ORIGEM,NOME_SMARTPHONE,PRECO_TABELA,MARCA,DATA_CADASTRO,LOGIN_USUARIO)
SELECT ID_SMARTPHONE, NOME_PRODUTO, VALOR_PRODUTO,'MOTOROLA',GETDATE(), SYSTEM_USER FROM MOTOROLA

INSERT INTO SMARTPHONE
(ID_TABELA_ORIGEM,NOME_SMARTPHONE,PRECO_TABELA,MARCA,DATA_CADASTRO,LOGIN_USUARIO)
SELECT ID_LG_SMARTPHONE, NOME_APARELHO, VALOR_COMERCIAL,'LG',GETDATE(), SYSTEM_USER FROM LG


--4-Crie um script, para atualizar os valores das tabelas criadas anteriormente.

--Atualize o preço do produto Smartphone LG K50S Preto para 700.00.
UPDATE SMARTPHONE SET PRECO_TABELA = 700 WHERE NOME_SMARTPHONE = 'Smartphone LG K50S Preto'

--Atualize o nome do produto Smartphone Moto G8 para Smartphone Moto G8 PLUS.
UPDATE SMARTPHONE SET NOME_SMARTPHONE = 'Smartphone Moto G8 PLUS' WHERE NOME_SMARTPHONE = 'Smartphone Moto G8'

--Atualiza a tabela SMARTPHONE, dobre o valor dos preços dos aparelhos da marca SAMSUNG.
UPDATE SMARTPHONE SET PRECO_TABELA = PRECO_TABELA * 2 WHERE MARCA = 'SAMSUNG'

--Atualiza a tabela SMARTPHONE, aplique um desconto de 10% nos preços dos aparelhos da marca LG que o preço seja maior que 1500.00.
UPDATE SMARTPHONE SET PRECO_TABELA = PRECO_TABELA - (PRECO_TABELA * 0.10) WHERE MARCA = 'LG'


--Atualize o campo DATA da tabela MOTOROLA, as datas que estão vazias devem conter a data de ’01-01-2016’
UPDATE MOTOROLA SET DATA = '01-01-2016' WHERE DATA IS NULL

--Atualize o campo DATA da tabela LG, as datas que estão vazias devem conter a data de ’01-01-2018’
UPDATE LG SET DATA_DISPONIBILIDADE = '01-01-2018' WHERE DATA_DISPONIBILIDADE IS NULL




--5-Crie um script, para deleção dos valores das tabelas criadas anteriormente

--Delete os valores da Tabela SAMSUNG que o preço é maior que 1300.00
DELETE SAMSUNG WHERE PRECO > 1300

--Delete os valores da Tabela LG que a DATA_DISPONIBILIDADE é maior que 08/08/2019
DELETE LG WHERE DATA_DISPONIBILIDADE > '08-08-2019'

--Delete os valores da Tabela MOTOROLA que a DATA é igual a 08/08/2018 e o preço igual 800
DELETE MOTOROLA WHERE DATA = '08-08-2018' AND VALOR_PRODUTO = 800


--Delete os valores da Tabela SMARTPHONE onde o ID_TABELA_ORIGEM é maior que 2.
DELETE SMARTPHONE WHERE ID_TABELA_ORIGEM > 2
