--GRUPO D


--1
UPDATE MAQUINA 
SET COR = 'Vermelha'
WHERE CODIGO <= 30

UPDATE MAQUINA 
SET COR = 'Preta'
WHERE CODIGO > 30 AND CODIGO <= 50

UPDATE MAQUINA 
SET COR = 'Azul'
WHERE CODIGO > 50

--2
INSERT INTO ESTADO (ESTADO, SIGLA)
VALUES
('GOIÁS', 'GO')

--3
UPDATE ESTADO
SET ESTADO = 'BAHIA'
WHERE SIGLA = 'BA'

ALTER TABLE ESTADO 
ALTER COLUMN ESTADO VARCHAR(200) NOT NULL

--4
DELETE ENDERECO
WHERE ID_ENDERECO = 8

--5
SELECT LOGRADOURO, NUMERO, CEP FROM ENDERECO
WHERE CEP NOT LIKE '%-%'

--6
INSERT INTO ESTADO (ESTADO, SIGLA)
VALUES
('AMAZONAS', 'AM')

INSERT INTO CIDADE (CIDADE, ID_ESTADO)
VALUES
('MANAUS', 6)

--7
ALTER TABLE CLIENTE
DROP COLUMN NOME_FANTASIA

--8
UPDATE CLIENTE
SET DATA_CADASTRO = '2012-01-01'
WHERE DATA_CADASTRO IS NULL

--9
SELECT DISTINCT ID_PEDIDO, C.NOME, DATEDIFF(YEAR, DATA_NASCIMENTO,GETDATE()) AS IDADE FROM PEDIDO P
INNER JOIN CLIENTE C
	ON P.ID_CLIENTE = C.ID_CLIENTE
WHERE 
	DATEDIFF(YEAR, DATA_NASCIMENTO,GETDATE()) < 18

--10
SELECT DISTINCT a.NOME 
FROM CLIENTE a
INNER JOIN ENDERECO b ON a.ID_ENDERECO = b.ID_ENDERECO
INNER JOIN CIDADE c ON b.ID_CIDADE = c.ID_CIDADE
INNER JOIN PEDIDO d ON a.ID_CLIENTE = d.ID_PEDIDO
INNER JOIN ITEM_PEDIDO e ON d.ID_PEDIDO = e.ID_PEDIDO
INNER JOIN MAQUINA f ON e.ID_MAQUINA = f.ID_MAQUINA
WHERE c.CIDADE = 'SÃO PAULO'

--11
SELECT DISTINCT MAQUINA.NOME FROM MAQUINA
INNER JOIN ITEM_PEDIDO ON ITEM_PEDIDO.ID_MAQUINA = MAQUINA.ID_MAQUINA
INNER JOIN PEDIDO ON PEDIDO.ID_PEDIDO = ITEM_PEDIDO.ID_PEDIDO
WHERE DATA_PEDIDO >= '2012-01-01' and DATA_PEDIDO < '2012-07-01'

--12
UPDATE MAQUINA
SET TIPO = ('PEBOLIM')
WHERE DESCRICAO LIKE '%PEBOLIM%'

UPDATE MAQUINA
SET TIPO = ('FLIPERAMA')
WHERE DESCRICAO LIKE '%FLIPERAMA%'

UPDATE MAQUINA
SET TIPO = ('CAÇA NIQUEL')
WHERE DESCRICAO LIKE '%NIQUEL%'

/*UPDATE MAQUINA
SET TIPO = CASE WHEN lower(DESCRICAO) LIKE ('%fliperama%') THEN 'FLIPERAMA' 
WHEN lower(DESCRICAO) LIKE ('%pebolim%') THEN 'PEBOLIM' 
WHEN lower(DESCRICAO) LIKE ('%caça niquel%') THEN 'CAÇA NIQUEL' END
*/

--13
SELECT PEDIDO.CONTRATO, MAQUINA.NOME AS NOME_MAQUINA, 
ITEM_PEDIDO.QUANTIDADE AS QUANTIDADE_POR_MAQUINA, 
PEDIDO.DATA_PEDIDO AS DATA_PEDIDO, 
ITEM_PEDIDO.VALOR_TOTAL AS VALOR_TOTAL_MAQUINA
INTO CONTRATO_MAQUINAS FROM PEDIDO
INNER JOIN ITEM_PEDIDO ON PEDIDO.ID_PEDIDO = ITEM_PEDIDO.ID_PEDIDO
INNER JOIN MAQUINA ON ITEM_PEDIDO.ID_MAQUINA = MAQUINA.ID_MAQUINA

--14
SELECT  C.NOME,
	C.CNPJ_CPF CPF_CLIENTE,
	C.DATA_NASCIMENTO,
	E.LOGRADOURO,
	E.NUMERO,
	E.CEP,
	D.CIDADE,
	T.SIGLA
FROM CLIENTE C 
	 INNER JOIN ENDERECO E 
		ON E.ID_ENDERECO = C.ID_ENDERECO
	 INNER JOIN CIDADE D
		ON D.ID_CIDADE = E.ID_CIDADE
	 INNER JOIN ESTADO T
		ON T.ID_ESTADO = D.ID_ESTADO
ORDER BY NOME

--15
SELECT 
a.CONTRATO, a.VALOR, a.QUANTIDADE, a.DATA_PEDIDO, a.VALOR_TOTAL, a.QUANTIDADE_TOTAL,
b.NOME, b.CNPJ_CPF AS CPF_CLIENTE, b.DATA_NASCIMENTO, c.LOGRADOURO, c.NUMERO, c.CEP,
d.CIDADE, e.SIGLA
FROM PEDIDO a
INNER JOIN CLIENTE b ON a.ID_CLIENTE = b.ID_CLIENTE
INNER JOIN ENDERECO c ON c.ID_ENDERECO = b.ID_ENDERECO
INNER JOIN CIDADE d ON c.ID_CIDADE = d.ID_CIDADE
INNER JOIN ESTADO e ON d.ID_ESTADO = e.ID_ESTADO
ORDER BY ID_PEDIDO

--16
SELECT C.NOME,
	C.EMAIL,
	E.LOGRADOURO,
	E.NUMERO,
	E.CEP,
	D.CIDADE
 INTO CLIENTES_MALA_DIRETA
FROM CLIENTE C
INNER JOIN ENDERECO E
	ON E.ID_ENDERECO = C.ID_ENDERECO
INNER JOIN CIDADE D
	ON D.ID_CIDADE = E.ID_CIDADE
WHERE 
	EMAIL NOT LIKE '%@%'
