CREATE TABLE 
PROGRAMA
(ID_PROGRAMA INT IDENTITY(1,1),
NOME_PROGRAMA VARCHAR(200),
CANAL VARCHAR(200),
LINGUA VARCHAR(200)
)
 
CREATE TABLE CANAL
(NOME VARCHAR(200),
PAIS VARCHAR(200)
)

INSERT INTO PROGRAMA 
VALUES 
('TESTE DE FIDELIDADE','REDETV',NULL),
('PROGRAMA DO RATINHO','SBT',NULL),
('CASOS DE FAMILIA','SBT',NULL),
('TRATO FEITO','HISTORY CHANNEL',NULL),
('LARGADOS E PELADOS','DISCOVERY CHANNEL',NULL)



INSERT INTO CANAL VALUES
('REDETV','BRASIL'),
('SBT','BRASIL'),
('HISTORY CHANNEL','EUA'),
('FOX','EUA')


SELECT P.NOME_PROGRAMA,C.NOME FROM PROGRAMA AS P
INNER JOIN CANAL AS C ON P.CANAL = C.NOME

SELECT P.NOME_PROGRAMA,P.CANAL,C.NOME  FROM PROGRAMA AS P
LEFT JOIN CANAL AS C ON P.CANAL = C.NOME


SELECT * FROM PROGRAMA AS P
RIGHT JOIN CANAL AS C ON P.CANAL = C.NOME

SELECT * FROM PROGRAMA AS P
FULL JOIN CANAL AS C ON P.CANAL = C.NOME

SELECT * FROM PROGRAMA AS P
CROSS JOIN CANAL C

BEGIN TRANSACTION
UPDATE PROGRAMA
SET LINGUA = 'PORTUGUES'
FROM PROGRAMA P INNER JOIN CANAL C
ON P.CANAL = C.NOME
WHERE C.PAIS = 'BRASIL'
ROLLBACK

BEGIN TRANSACTION
DELETE PROGRAMA 
FROM PROGRAMA P INNER JOIN CANAL C
ON P.CANAL = C.NOME
WHERE C.PAIS = 'EUA'
SELECT * FROM PROGRAMA
ROLLBACK 

 
CREATE TABLE FUNCIONARIO 
(ID_FUNCIONARIO INT IDENTITY (1,1) PRIMARY KEY,
NOME VARCHAR(MAX),
CARGO VARCHAR(500),
ID_GESTOR INT FOREIGN KEY REFERENCES FUNCIONARIO(ID_FUNCIONARIO),
DATA_CONTRATACAO DATE)

INSERT INTO FUNCIONARIO
VALUES 
('ALMEIDA JUNIOR','GERENTE',NULL,'2020-01-01'),
('CARLOS EDUARDO','ANALISTA',1,'2020-03-01'),
('CATIA ANDRADE','ANALISTA',1,'2020-06-01'),
('FELIPE SILVA','ESTAGIARIO',3,'2020-09-01')

SELECT * FROM FUNCIONARIO 


SELECT 
FUNCIONARIO.ID_FUNCIONARIO,
FUNCIONARIO.NOME FUNCIONARIO ,
FUNCIONARIO.CARGO CARGO,
FUNCIONARIO.ID_GESTOR,
GERENTE.NOME AS GESTOR,
CARGO_GESTOR = GERENTE.CARGO 
FROM FUNCIONARIO 
LEFT JOIN FUNCIONARIO AS GERENTE ON FUNCIONARIO.ID_GESTOR = GERENTE.ID_FUNCIONARIO
--ALMEIDA JUNIOR + 1 = 2
SELECT 
FUNCIONARIO.ID_FUNCIONARIO,
FUNCIONARIO.NOME FUNCIONARIO ,
FUNCIONARIO.DATA_CONTRATACAO,

ANTERIOR.ID_FUNCIONARIO ID_ANTERIOR,
ANTERIOR.NOME  FUNCIONARIO_ANTERIOR ,
ANTERIOR.DATA_CONTRATACAO DATA_CONTRATACAO_ANTERIOR,
DIFERENÇA_DIAS = DATEDIFF(DAY,ANTERIOR.DATA_CONTRATACAO,FUNCIONARIO.DATA_CONTRATACAO)
FROM FUNCIONARIO 
LEFT JOIN FUNCIONARIO AS ANTERIOR ON FUNCIONARIO.ID_FUNCIONARIO = ANTERIOR.ID_FUNCIONARIO + 1