USE MASTER 
DROP DATABASE IF EXISTS PAPEL
GO
CREATE DATABASE PAPEL
GO
 USE PAPEL
CREATE TABLE FORNECEDOR_PAPEL
(
ID_FORNECEDOR_PAPEL  INT IDENTITY(1,1) PRIMARY KEY,
NOME_FORNECEDOR VARCHAR(MAX)
)
CREATE TABLE PAPEL
(
ID_PAPEL INT IDENTITY(1,1) PRIMARY KEY,
NOME_PAPEL VARCHAR(200) UNIQUE,
CODIGO_PAPEL VARCHAR(200)  ,
ID_FORNECEDOR_PAPEL INT FOREIGN KEY REFERENCES FORNECEDOR_PAPEL(ID_FORNECEDOR_PAPEL)
)
CREATE TABLE CLIENTE_PAPEL
(
ID_CLIENTE_PAPEL INT IDENTITY(1,1) PRIMARY KEY,
NOME_CLIENTE_PAPEL VARCHAR(200)
)
CREATE TABLE PEDIDO_PAPEL
(
ID_PEDIDO_PAPEL INT IDENTITY(1,1) PRIMARY KEY,
NUMERO_PEDIDO_PAPEL INT  ,
QUANTIDADE_TOTAL INT,
VALOR_TOTAL DECIMAL(10,2),
DATA DATE,
ID_CLIENTE_PAPEL INT FOREIGN KEY REFERENCES CLIENTE_PAPEL(ID_CLIENTE_PAPEL)
)
CREATE TABLE DETALHE_PEDIDO_PAPEL
(
ID_DETALHE_PEDIDO_PAPEL INT IDENTITY(1,1) PRIMARY KEY,
ID_PAPEL  INT FOREIGN KEY REFERENCES PAPEL(ID_PAPEL),
QUANTIDADE INT,
VALOR DECIMAL(10,2),
ID_PEDIDO_PAPEL INT FOREIGN KEY REFERENCES PEDIDO_PAPEL(ID_PEDIDO_PAPEL)
)
INSERT INTO FORNECEDOR_PAPEL  VALUES 
('FORNECEDOR PAPEL V'),('FORNECEDOR PAPEL C')
INSERT INTO PAPEL (NOME_PAPEL,ID_FORNECEDOR_PAPEL,CODIGO_PAPEL) VALUES
('PAPEL V',1,'V_PAPEL'),('PAPEL V2',1,'V2_PAPEL'),('PAPEL C',2,'C_PAPEL'),('PAPEL C2',2,'C2_PAPEL')
,('PAPEL ZY',2,'ZY_PAPEL')
INSERT INTO CLIENTE_PAPEL VALUES
('PAPEL VC INC.') , ('CCV PAPEL VENDAS SA')
INSERT INTO PEDIDO_PAPEL 
(NUMERO_PEDIDO_PAPEL,QUANTIDADE_TOTAL,VALOR_TOTAL,DATA,ID_CLIENTE_PAPEL) VALUES
(100,2,1000,'2000-01-01',1),
(150,1,500,'2000-02-01',2),
(180,1,500,'2000-03-01',2),
(190,3,1500,'2000-04-01',2)
INSERT INTO DETALHE_PEDIDO_PAPEL (ID_PAPEL,QUANTIDADE,VALOR,ID_PEDIDO_PAPEL) VALUES
(1,1,500,1),
(2,1,500,1),
(1,1,500,2),
(2,1,500,3), 
(3,1,500,4),
(4,2,1000,4)
 /*
 Ola Mayra Fernanda Silvage tudo bem com você? Preciso de uma ajuda aqui para entregar um relatório. Da uma força!
1 - Poderia selecionar o nome dos PAPELS e o nome do fornecedor dos PAPELS 
    onde o codigo do PAPEL não  começe com C, ordenados pelo nome do PAPEL?
*/
/*
2 - Poderia selecionar o nome dos clientes a data do pedido do PAPEL, quantidade e  valor
    onde a data do pedido é maior que 2000-03-01?
*/
/*
3 - Poderia criar uma tabela chamada [COMPRAS_PAPEL] com os valores
o nome do PAPEL, o nome do cliente, data da compra ?
*/

/*
4 - Poderia criar uma consulta, para buscar o NOME dos PAPELS que não tiveram nenhuma compra?
(PS: OBRIGATÓRIO TER UM JOIN ENTRE A TABELA PAPEL E PEDIDO_PAPEL, 
NADA DE SELECT * FROM PAPELS where NOME = XXX não!
*/
 /*
5 - Poderia criar uma tabela chamada [COMPRAS_PAPEL_FORNECEDOR] com os valores
o nome do PAPEL, quantidade do PAPEL vendida, o valor e o nome do fornecedor onde o 
nome do fornecedor não   termine com a letra V? */