USE MASTER 
DROP DATABASE IF EXISTS MARTELO
GO
CREATE DATABASE MARTELO
GO
 USE MARTELO
CREATE TABLE FORNECEDOR_MARTELO
(
ID_FORNECEDOR_MARTELO  INT IDENTITY(1,1) PRIMARY KEY,
NOME_FORNECEDOR VARCHAR(MAX)
)
CREATE TABLE MARTELO
(
ID_MARTELO INT IDENTITY(1,1) PRIMARY KEY,
NOME_MARTELO VARCHAR(200) UNIQUE,
CODIGO_MARTELO VARCHAR(200)  ,
ID_FORNECEDOR_MARTELO INT FOREIGN KEY REFERENCES FORNECEDOR_MARTELO(ID_FORNECEDOR_MARTELO)
)
CREATE TABLE CLIENTE_MARTELO
(
ID_CLIENTE_MARTELO INT IDENTITY(1,1) PRIMARY KEY,
NOME_CLIENTE_MARTELO VARCHAR(200)
)
CREATE TABLE PEDIDO_MARTELO
(
ID_PEDIDO_MARTELO INT IDENTITY(1,1) PRIMARY KEY,
NUMERO_PEDIDO_MARTELO INT  ,
QUANTIDADE_TOTAL INT,
VALOR_TOTAL DECIMAL(10,2),
DATA DATE,
ID_CLIENTE_MARTELO INT FOREIGN KEY REFERENCES CLIENTE_MARTELO(ID_CLIENTE_MARTELO)
)
CREATE TABLE DETALHE_PEDIDO_MARTELO
(
ID_DETALHE_PEDIDO_MARTELO INT IDENTITY(1,1) PRIMARY KEY,
ID_MARTELO  INT FOREIGN KEY REFERENCES MARTELO(ID_MARTELO),
QUANTIDADE INT,
VALOR DECIMAL(10,2),
ID_PEDIDO_MARTELO INT FOREIGN KEY REFERENCES PEDIDO_MARTELO(ID_PEDIDO_MARTELO)
)
INSERT INTO FORNECEDOR_MARTELO  VALUES 
('FORNECEDOR MARTELO O'),('FORNECEDOR MARTELO J')
INSERT INTO MARTELO (NOME_MARTELO,ID_FORNECEDOR_MARTELO,CODIGO_MARTELO) VALUES
('MARTELO O',1,'O_MARTELO'),('MARTELO O2',1,'O2_MARTELO'),('MARTELO J',2,'J_MARTELO'),('MARTELO J2',2,'J2_MARTELO')
,('MARTELO ZY',2,'ZY_MARTELO')
INSERT INTO CLIENTE_MARTELO VALUES
('MARTELO OJ INC.') , ('JJO MARTELO VENDAS SA')
INSERT INTO PEDIDO_MARTELO 
(NUMERO_PEDIDO_MARTELO,QUANTIDADE_TOTAL,VALOR_TOTAL,DATA,ID_CLIENTE_MARTELO) VALUES
(100,2,1000,'2000-01-01',1),
(150,1,500,'2000-02-01',2),
(180,1,500,'2000-03-01',2),
(190,3,1500,'2000-04-01',2)
INSERT INTO DETALHE_PEDIDO_MARTELO (ID_MARTELO,QUANTIDADE,VALOR,ID_PEDIDO_MARTELO) VALUES
(1,1,500,1),
(2,1,500,1),
(1,1,500,2),
(2,1,500,3), 
(3,1,500,4),
(4,2,1000,4)
 /*
 Ola Ketely Cristiny Brandebusque tudo bem com você? Preciso de uma ajuda aqui para entregar um relatório. Da uma força!
1 - Poderia selecionar o nome dos MARTELOS e o nome do fornecedor dos MARTELOS 
    onde o codigo do MARTELO    começe com J, ordenados pelo nome do MARTELO?
*/
/*
2 - Poderia selecionar o nome dos clientes a data do pedido do MARTELO, quantidade e  valor
    onde a data do pedido é maior que 2000-03-01?
*/
/*
3 - Poderia criar uma tabela chamada [COMPRAS_MARTELO] com os valores
o nome do MARTELO, o nome do cliente, data da compra ?
*/

/*
4 - Poderia criar uma consulta, para buscar o NOME dos MARTELOS que   tiveram nenhuma compra?
(PS: OBRIGATÓRIO TER UM JOIN ENTRE A TABELA MARTELO E PEDIDO_MARTELO, 
NADA DE SELECT * FROM MARTELOS where NOME = XXX não!
*/
 /*
5 - Poderia criar uma tabela chamada [COMPRAS_MARTELO_FORNECEDOR] com os valores
o nome do MARTELO, quantidade do MARTELO vendida, o valor e o nome do fornecedor onde o 
nome do fornecedor     termine com a letra O? */