USE MASTER 
DROP DATABASE IF EXISTS CACHORRO
GO
CREATE DATABASE CACHORRO
GO
 USE CACHORRO
CREATE TABLE FORNECEDOR_CACHORRO
(
ID_FORNECEDOR_CACHORRO  INT IDENTITY(1,1) PRIMARY KEY,
NOME_FORNECEDOR VARCHAR(MAX)
)
CREATE TABLE CACHORRO
(
ID_CACHORRO INT IDENTITY(1,1) PRIMARY KEY,
NOME_CACHORRO VARCHAR(200) UNIQUE,
CODIGO_CACHORRO VARCHAR(200)  ,
ID_FORNECEDOR_CACHORRO INT FOREIGN KEY REFERENCES FORNECEDOR_CACHORRO(ID_FORNECEDOR_CACHORRO)
)
CREATE TABLE CLIENTE_CACHORRO
(
ID_CLIENTE_CACHORRO INT IDENTITY(1,1) PRIMARY KEY,
NOME_CLIENTE_CACHORRO VARCHAR(200)
)
CREATE TABLE PEDIDO_CACHORRO
(
ID_PEDIDO_CACHORRO INT IDENTITY(1,1) PRIMARY KEY,
NUMERO_PEDIDO_CACHORRO INT  ,
QUANTIDADE_TOTAL INT,
VALOR_TOTAL DECIMAL(10,2),
DATA DATE,
ID_CLIENTE_CACHORRO INT FOREIGN KEY REFERENCES CLIENTE_CACHORRO(ID_CLIENTE_CACHORRO)
)
CREATE TABLE DETALHE_PEDIDO_CACHORRO
(
ID_DETALHE_PEDIDO_CACHORRO INT IDENTITY(1,1) PRIMARY KEY,
ID_CACHORRO  INT FOREIGN KEY REFERENCES CACHORRO(ID_CACHORRO),
QUANTIDADE INT,
VALOR DECIMAL(10,2),
ID_PEDIDO_CACHORRO INT FOREIGN KEY REFERENCES PEDIDO_CACHORRO(ID_PEDIDO_CACHORRO)
)
INSERT INTO FORNECEDOR_CACHORRO  VALUES 
('FORNECEDOR CACHORRO Q'),('FORNECEDOR CACHORRO H')
INSERT INTO CACHORRO (NOME_CACHORRO,ID_FORNECEDOR_CACHORRO,CODIGO_CACHORRO) VALUES
('CACHORRO Q',1,'Q_CACHORRO'),('CACHORRO Q2',1,'Q2_CACHORRO'),('CACHORRO H',2,'H_CACHORRO'),('CACHORRO H2',2,'H2_CACHORRO')
,('CACHORRO ZY',2,'ZY_CACHORRO')
INSERT INTO CLIENTE_CACHORRO VALUES
('CACHORRO QH INC.') , ('HHQ CACHORRO VENDAS SA')
INSERT INTO PEDIDO_CACHORRO 
(NUMERO_PEDIDO_CACHORRO,QUANTIDADE_TOTAL,VALOR_TOTAL,DATA,ID_CLIENTE_CACHORRO) VALUES
(100,2,1000,'2000-01-01',1),
(150,1,500,'2000-02-01',2),
(180,1,500,'2000-03-01',2),
(190,3,1500,'2000-04-01',2)
INSERT INTO DETALHE_PEDIDO_CACHORRO (ID_CACHORRO,QUANTIDADE,VALOR,ID_PEDIDO_CACHORRO) VALUES
(1,1,500,1),
(2,1,500,1),
(1,1,500,2),
(2,1,500,3), 
(3,1,500,4),
(4,2,1000,4)
 /*
 Ola Lucas Buroffi Cagnini tudo bem com você? Preciso de uma ajuda aqui para entregar um relatório. Da uma força!
1 - Poderia selecionar o nome dos CACHORROS e o nome do fornecedor dos CACHORROS 
    onde o codigo do CACHORRO    começe com H, ordenados pelo nome do CACHORRO?
*/
/*
2 - Poderia selecionar o nome dos clientes a data do pedido do CACHORRO, quantidade e  valor
    onde a data do pedido é maior que 2000-03-01?
*/
/*
3 - Poderia criar uma tabela chamada [COMPRAS_CACHORRO] com os valores
o nome do CACHORRO, o nome do cliente, data da compra ?
*/

/*
4 - Poderia criar uma consulta, para buscar o NOME dos CACHORROS que   tiveram nenhuma compra?
(PS: OBRIGATÓRIO TER UM JOIN ENTRE A TABELA CACHORRO E PEDIDO_CACHORRO, 
NADA DE SELECT * FROM CACHORROS where NOME = XXX não!
*/
 /*
5 - Poderia criar uma tabela chamada [COMPRAS_CACHORRO_FORNECEDOR] com os valores
o nome do CACHORRO, quantidade do CACHORRO vendida, o valor e o nome do fornecedor onde o 
nome do fornecedor     termine com a letra Q? */