USE MASTER 
DROP DATABASE IF EXISTS DVD
GO
CREATE DATABASE DVD
GO
 USE DVD
CREATE TABLE FORNECEDOR_DVD
(
ID_FORNECEDOR_DVD  INT IDENTITY(1,1) PRIMARY KEY,
NOME_FORNECEDOR VARCHAR(MAX)
)
CREATE TABLE DVD
(
ID_DVD INT IDENTITY(1,1) PRIMARY KEY,
NOME_DVD VARCHAR(200) UNIQUE,
CODIGO_DVD VARCHAR(200)  ,
ID_FORNECEDOR_DVD INT FOREIGN KEY REFERENCES FORNECEDOR_DVD(ID_FORNECEDOR_DVD)
)
CREATE TABLE CLIENTE_DVD
(
ID_CLIENTE_DVD INT IDENTITY(1,1) PRIMARY KEY,
NOME_CLIENTE_DVD VARCHAR(200)
)
CREATE TABLE PEDIDO_DVD
(
ID_PEDIDO_DVD INT IDENTITY(1,1) PRIMARY KEY,
NUMERO_PEDIDO_DVD INT  ,
QUANTIDADE_TOTAL INT,
VALOR_TOTAL DECIMAL(10,2),
DATA DATE,
ID_CLIENTE_DVD INT FOREIGN KEY REFERENCES CLIENTE_DVD(ID_CLIENTE_DVD)
)
CREATE TABLE DETALHE_PEDIDO_DVD
(
ID_DETALHE_PEDIDO_DVD INT IDENTITY(1,1) PRIMARY KEY,
ID_DVD  INT FOREIGN KEY REFERENCES DVD(ID_DVD),
QUANTIDADE INT,
VALOR DECIMAL(10,2),
ID_PEDIDO_DVD INT FOREIGN KEY REFERENCES PEDIDO_DVD(ID_PEDIDO_DVD)
)
INSERT INTO FORNECEDOR_DVD  VALUES 
('FORNECEDOR DVD B'),('FORNECEDOR DVD W')
INSERT INTO DVD (NOME_DVD,ID_FORNECEDOR_DVD,CODIGO_DVD) VALUES
('DVD B',1,'B_DVD'),('DVD B2',1,'B2_DVD'),('DVD W',2,'W_DVD'),('DVD W2',2,'W2_DVD')
,('DVD ZY',2,'ZY_DVD')
INSERT INTO CLIENTE_DVD VALUES
('DVD BW INC.') , ('WWB DVD VENDAS SA')
INSERT INTO PEDIDO_DVD 
(NUMERO_PEDIDO_DVD,QUANTIDADE_TOTAL,VALOR_TOTAL,DATA,ID_CLIENTE_DVD) VALUES
(100,2,1000,'2000-01-01',1),
(150,1,500,'2000-02-01',2),
(180,1,500,'2000-03-01',2),
(190,3,1500,'2000-04-01',2)
INSERT INTO DETALHE_PEDIDO_DVD (ID_DVD,QUANTIDADE,VALOR,ID_PEDIDO_DVD) VALUES
(1,1,500,1),
(2,1,500,1),
(1,1,500,2),
(2,1,500,3), 
(3,1,500,4),
(4,2,1000,4)
 /*
 Ola Pedro Luiz Soares Santos tudo bem com você? Preciso de uma ajuda aqui para entregar um relatório. Da uma força!
1 - Poderia selecionar o nome dos DVDS e o nome do fornecedor dos DVDS 
    onde o codigo do DVD    começe com W, ordenados pelo nome do DVD?
*/
/*
2 - Poderia selecionar o nome dos clientes a data do pedido do DVD, quantidade e  valor
    onde a data do pedido é maior que 2000-03-01?
*/
/*
3 - Poderia criar uma tabela chamada [COMPRAS_DVD] com os valores
o nome do DVD, o nome do cliente, data da compra ?
*/

/*
4 - Poderia criar uma consulta, para buscar o NOME dos DVDS que   tiveram nenhuma compra?
(PS: OBRIGATÓRIO TER UM JOIN ENTRE A TABELA DVD E PEDIDO_DVD, 
NADA DE SELECT * FROM DVDS where NOME = XXX não!
*/
 /*
5 - Poderia criar uma tabela chamada [COMPRAS_DVD_FORNECEDOR] com os valores
o nome do DVD, quantidade do DVD vendida, o valor e o nome do fornecedor onde o 
nome do fornecedor     termine com a letra B? */