USE MASTER 
DROP DATABASE IF EXISTS OVO
GO
CREATE DATABASE OVO
GO
 USE OVO
CREATE TABLE FORNECEDOR_OVO
(
ID_FORNECEDOR_OVO  INT IDENTITY(1,1) PRIMARY KEY,
NOME_FORNECEDOR VARCHAR(MAX)
)
CREATE TABLE OVO
(
ID_OVO INT IDENTITY(1,1) PRIMARY KEY,
NOME_OVO VARCHAR(200) UNIQUE,
CODIGO_OVO VARCHAR(200)  ,
ID_FORNECEDOR_OVO INT FOREIGN KEY REFERENCES FORNECEDOR_OVO(ID_FORNECEDOR_OVO)
)
CREATE TABLE CLIENTE_OVO
(
ID_CLIENTE_OVO INT IDENTITY(1,1) PRIMARY KEY,
NOME_CLIENTE_OVO VARCHAR(200)
)
CREATE TABLE PEDIDO_OVO
(
ID_PEDIDO_OVO INT IDENTITY(1,1) PRIMARY KEY,
NUMERO_PEDIDO_OVO INT  ,
QUANTIDADE_TOTAL INT,
VALOR_TOTAL DECIMAL(10,2),
DATA DATE,
ID_CLIENTE_OVO INT FOREIGN KEY REFERENCES CLIENTE_OVO(ID_CLIENTE_OVO)
)
CREATE TABLE DETALHE_PEDIDO_OVO
(
ID_DETALHE_PEDIDO_OVO INT IDENTITY(1,1) PRIMARY KEY,
ID_OVO  INT FOREIGN KEY REFERENCES OVO(ID_OVO),
QUANTIDADE INT,
VALOR DECIMAL(10,2),
ID_PEDIDO_OVO INT FOREIGN KEY REFERENCES PEDIDO_OVO(ID_PEDIDO_OVO)
)
INSERT INTO FORNECEDOR_OVO  VALUES 
('FORNECEDOR OVO M'),('FORNECEDOR OVO L')
INSERT INTO OVO (NOME_OVO,ID_FORNECEDOR_OVO,CODIGO_OVO) VALUES
('OVO M',1,'M_OVO'),('OVO M2',1,'M2_OVO'),('OVO L',2,'L_OVO'),('OVO L2',2,'L2_OVO')
,('OVO ZY',2,'ZY_OVO')
INSERT INTO CLIENTE_OVO VALUES
('OVO ML INC.') , ('LLM OVO VENDAS SA')
INSERT INTO PEDIDO_OVO 
(NUMERO_PEDIDO_OVO,QUANTIDADE_TOTAL,VALOR_TOTAL,DATA,ID_CLIENTE_OVO) VALUES
(100,2,1000,'2000-01-01',1),
(150,1,500,'2000-02-01',2),
(180,1,500,'2000-03-01',2),
(190,3,1500,'2000-04-01',2)
INSERT INTO DETALHE_PEDIDO_OVO (ID_OVO,QUANTIDADE,VALOR,ID_PEDIDO_OVO) VALUES
(1,1,500,1),
(2,1,500,1),
(1,1,500,2),
(2,1,500,3), 
(3,1,500,4),
(4,2,1000,4)
 /*
 Ola Isaque Ribeiro dos Santos Junior tudo bem com você? Preciso de uma ajuda aqui para entregar um relatório. Da uma força!
1 - Poderia selecionar o nome dos OVOS e o nome do fornecedor dos OVOS 
    onde o codigo do OVO    começe com L, ordenados pelo nome do OVO?
*/
/*
2 - Poderia selecionar o nome dos clientes a data do pedido do OVO, quantidade e  valor
    onde a data do pedido é maior que 2000-03-01?
*/
/*
3 - Poderia criar uma tabela chamada [COMPRAS_OVO] com os valores
o nome do OVO, o nome do cliente, data da compra ?
*/

/*
4 - Poderia criar uma consulta, para buscar o NOME dos OVOS que   tiveram nenhuma compra?
(PS: OBRIGATÓRIO TER UM JOIN ENTRE A TABELA OVO E PEDIDO_OVO, 
NADA DE SELECT * FROM OVOS where NOME = XXX não!
*/
 /*
5 - Poderia criar uma tabela chamada [COMPRAS_OVO_FORNECEDOR] com os valores
o nome do OVO, quantidade do OVO vendida, o valor e o nome do fornecedor onde o 
nome do fornecedor     termine com a letra M? */