USE MASTER 
DROP DATABASE IF EXISTS MOTO
GO
CREATE DATABASE MOTO
GO
 USE MOTO
CREATE TABLE FORNECEDOR_MOTO
(
ID_FORNECEDOR_MOTO  INT IDENTITY(1,1) PRIMARY KEY,
NOME_FORNECEDOR VARCHAR(MAX)
)
CREATE TABLE MOTO
(
ID_MOTO INT IDENTITY(1,1) PRIMARY KEY,
NOME_MOTO VARCHAR(200) UNIQUE,
CODIGO_MOTO VARCHAR(200)  ,
ID_FORNECEDOR_MOTO INT FOREIGN KEY REFERENCES FORNECEDOR_MOTO(ID_FORNECEDOR_MOTO)
)
CREATE TABLE CLIENTE_MOTO
(
ID_CLIENTE_MOTO INT IDENTITY(1,1) PRIMARY KEY,
NOME_CLIENTE_MOTO VARCHAR(200)
)
CREATE TABLE PEDIDO_MOTO
(
ID_PEDIDO_MOTO INT IDENTITY(1,1) PRIMARY KEY,
NUMERO_PEDIDO_MOTO INT  ,
QUANTIDADE_TOTAL INT,
VALOR_TOTAL DECIMAL(10,2),
DATA DATE,
ID_CLIENTE_MOTO INT FOREIGN KEY REFERENCES CLIENTE_MOTO(ID_CLIENTE_MOTO)
)
CREATE TABLE DETALHE_PEDIDO_MOTO
(
ID_DETALHE_PEDIDO_MOTO INT IDENTITY(1,1) PRIMARY KEY,
ID_MOTO  INT FOREIGN KEY REFERENCES MOTO(ID_MOTO),
QUANTIDADE INT,
VALOR DECIMAL(10,2),
ID_PEDIDO_MOTO INT FOREIGN KEY REFERENCES PEDIDO_MOTO(ID_PEDIDO_MOTO)
)
INSERT INTO FORNECEDOR_MOTO  VALUES 
('FORNECEDOR MOTO R'),('FORNECEDOR MOTO G')
INSERT INTO MOTO (NOME_MOTO,ID_FORNECEDOR_MOTO,CODIGO_MOTO) VALUES
('MOTO R',1,'R_MOTO'),('MOTO R2',1,'R2_MOTO'),('MOTO G',2,'G_MOTO'),('MOTO G2',2,'G2_MOTO')
,('MOTO ZY',2,'ZY_MOTO')
INSERT INTO CLIENTE_MOTO VALUES
('MOTO RG INC.') , ('GGR MOTO VENDAS SA')
INSERT INTO PEDIDO_MOTO 
(NUMERO_PEDIDO_MOTO,QUANTIDADE_TOTAL,VALOR_TOTAL,DATA,ID_CLIENTE_MOTO) VALUES
(100,2,1000,'2000-01-01',1),
(150,1,500,'2000-02-01',2),
(180,1,500,'2000-03-01',2),
(190,3,1500,'2000-04-01',2)
INSERT INTO DETALHE_PEDIDO_MOTO (ID_MOTO,QUANTIDADE,VALOR,ID_PEDIDO_MOTO) VALUES
(1,1,500,1),
(2,1,500,1),
(1,1,500,2),
(2,1,500,3), 
(3,1,500,4),
(4,2,1000,4)
 /*
 Ola Lucimara Mendes da Silva tudo bem com você? Preciso de uma ajuda aqui para entregar um relatório. Da uma força!
1 - Poderia selecionar o nome dos MOTOS e o nome do fornecedor dos MOTOS 
    onde o codigo do MOTO não  começe com G, ordenados pelo nome do MOTO?
*/
/*
2 - Poderia selecionar o nome dos clientes a data do pedido do MOTO, quantidade e  valor
    onde a data do pedido é maior que 2000-03-01?
*/
/*
3 - Poderia criar uma tabela chamada [COMPRAS_MOTO] com os valores
o nome do MOTO, o nome do cliente, data da compra ?
*/

/*
4 - Poderia criar uma consulta, para buscar o NOME dos MOTOS que não tiveram nenhuma compra?
(PS: OBRIGATÓRIO TER UM JOIN ENTRE A TABELA MOTO E PEDIDO_MOTO, 
NADA DE SELECT * FROM MOTOS where NOME = XXX não!
*/
 /*
5 - Poderia criar uma tabela chamada [COMPRAS_MOTO_FORNECEDOR] com os valores
o nome do MOTO, quantidade do MOTO vendida, o valor e o nome do fornecedor onde o 
nome do fornecedor não   termine com a letra R? */