USE MASTER 
DROP DATABASE IF EXISTS PAPEL
GO
CREATE DATABASE PAPEL
GO
 USE PAPEL
go

CREATE TABLE FORNECEDOR_PAPEL
(
ID_FORNECEDOR_PAPEL  INT IDENTITY(1,1) PRIMARY KEY,
NOME_FORNECEDOR VARCHAR(MAX)
)
GO
CREATE TABLE PAPEL
(
ID_PAPEL INT IDENTITY(1,1) PRIMARY KEY,
NOME_PAPEL VARCHAR(200) UNIQUE,
CODIGO_PAPEL VARCHAR(200)  ,
ID_FORNECEDOR_PAPEL INT FOREIGN KEY REFERENCES FORNECEDOR_PAPEL(ID_FORNECEDOR_PAPEL)
) 
GO
CREATE TABLE CLIENTE_PAPEL
(
ID_CLIENTE_PAPEL INT IDENTITY(1,1) PRIMARY KEY,
NOME_CLIENTE_PAPEL VARCHAR(200)
)
GO
CREATE TABLE PEDIDO_PAPEL
(
ID_PEDIDO_PAPEL INT IDENTITY(1,1) PRIMARY KEY,
NUMERO_PEDIDO_PAPEL INT  ,
QUANTIDADE_TOTAL INT,
VALOR_TOTAL DECIMAL(10,2),
DATA DATE,
ID_CLIENTE_PAPEL INT FOREIGN KEY REFERENCES CLIENTE_PAPEL(ID_CLIENTE_PAPEL)
)
GO
CREATE TABLE DETALHE_PEDIDO_PAPEL
(
ID_DETALHE_PEDIDO_PAPEL INT IDENTITY(1,1) PRIMARY KEY,
ID_PAPEL  INT FOREIGN KEY REFERENCES PAPEL(ID_PAPEL),
QUANTIDADE INT,
VALOR DECIMAL(10,2),
ID_PEDIDO_PAPEL INT FOREIGN KEY REFERENCES PEDIDO_PAPEL(ID_PEDIDO_PAPEL)
)
GO


INSERT INTO FORNECEDOR_PAPEL  VALUES 
('FORNECEDOR PAPEL J'),('FORNECEDOR PAPEL O')
GO
INSERT INTO PAPEL (NOME_PAPEL,ID_FORNECEDOR_PAPEL,CODIGO_PAPEL) VALUES
('PAPEL J',1,'J_PAPEL'),('PAPEL J2',1,'J2_PAPEL'),('PAPEL O',2,'O_PAPEL'),('PAPEL O2',2,'O2_PAPEL')
,('PAPEL ZY',2,'ZY_PAPEL')
GO
INSERT INTO CLIENTE_PAPEL VALUES
('PAPEL JO INC.') , ('OOJ PAPEL VENDAS SA')
GO
INSERT INTO PEDIDO_PAPEL 
(NUMERO_PEDIDO_PAPEL,QUANTIDADE_TOTAL,VALOR_TOTAL,DATA,ID_CLIENTE_PAPEL) VALUES
(100,2,1000,'2000-01-01',1),
(150,1,500,'2000-02-01',2),
(180,1,500,'2000-03-01',2),
(190,3,1500,'2000-04-01',2)
GO
INSERT INTO DETALHE_PEDIDO_PAPEL (ID_PAPEL,QUANTIDADE,VALOR,ID_PEDIDO_PAPEL) VALUES
(1,1,500,1),
(2,1,500,1),
(1,1,500,2),
(2,1,500,3), 
(3,1,500,4),
(4,2,1000,4)
GO

 /*
 Ola Gabriel Serrano Scalione tudo bem com você? Preciso de uma ajuda aqui para entregar um relatório. Da uma força!
1 - Poderia selecionar o nome dos PAPELS e o nome do fornecedor dos PAPELS 
    onde o codigo do PAPEL não  começe com O, ordenados pelo nome do PAPEL?
*/
	SELECT 
		NOME_PAPEL,
		NOME_FORNECEDOR
	FROM PAPEL P
		INNER JOIN FORNECEDOR_PAPEL F
			ON F.ID_FORNECEDOR_PAPEL = P.ID_FORNECEDOR_PAPEL
	WHERE 
		CODIGO_PAPEL NOT LIKE 'O%'
	ORDER BY
		NOME_PAPEL
GO

/*
2 - Poderia selecionar o nome dos clientes a data do pedido do PAPEL, quantidade e  valor
    onde a data do pedido é maior que 2000-03-01?
*/
	SELECT 
		C.NOME_CLIENTE_PAPEL,
		P.DATA,
		L.NOME_PAPEL,
		D.QUANTIDADE,
		D.VALOR
	FROM 
		CLIENTE_PAPEL C
		INNER JOIN PEDIDO_PAPEL P
			ON P.ID_CLIENTE_PAPEL = C.ID_CLIENTE_PAPEL
		INNER JOIN DETALHE_PEDIDO_PAPEL D
			ON P.ID_PEDIDO_PAPEL = D.ID_PEDIDO_PAPEL
		INNER JOIN PAPEL L
			ON L.ID_PAPEL = D.ID_PAPEL
	WHERE 
		P.DATA > '2000-03-01'
GO

/*
3 - Poderia criar uma tabela chamada [COMPRAS_PAPEL] com os valores
o nome do PAPEL, o nome do cliente, data da compra ?
*/
	SELECT 
		C.NOME_CLIENTE_PAPEL,
		P.DATA,
		L.NOME_PAPEL,
		D.VALOR
	
		INTO COMPRAS_PAPEL

	FROM 
		CLIENTE_PAPEL C
		INNER JOIN PEDIDO_PAPEL P
			ON P.ID_CLIENTE_PAPEL = C.ID_CLIENTE_PAPEL
		INNER JOIN DETALHE_PEDIDO_PAPEL D
			ON P.ID_PEDIDO_PAPEL = D.ID_PEDIDO_PAPEL
		INNER JOIN PAPEL L
			ON L.ID_PAPEL = D.ID_PAPEL

	SELECT * FROM COMPRAS_PAPEL
GO
/*
4 - Poderia criar uma consulta, para buscar o NOME dos PAPELS que não tiveram nenhuma compra?
(PS: OBRIGATÓRIO TER UM JOIN ENTRE A TABELA PAPEL E PEDIDO_PAPEL, 
NADA DE SELECT * FROM PAPELS where NOME = XXX não!
*/
	SELECT 
		P.NOME_PAPEL
	FROM 
		PAPEL P
		LEFT JOIN DETALHE_PEDIDO_PAPEL D
			ON D.ID_PAPEL = P.ID_PAPEL
		LEFT JOIN PEDIDO_PAPEL E
			ON E.ID_PEDIDO_PAPEL = D.ID_PEDIDO_PAPEL
	WHERE
		E.ID_PEDIDO_PAPEL IS NULL
GO
 /*
5 - Poderia criar uma tabela chamada [COMPRAS_PAPEL_FORNECEDOR] com os valores
o nome do PAPEL, quantidade do PAPEL vendida, o valor e o nome do fornecedor onde o 
nome do fornecedor não   termine com a letra J? 
*/
	SELECT 
		P.NOME_PAPEL,
		D.QUANTIDADE,
		D.VALOR,
		F.NOME_FORNECEDOR
	
		INTO COMPRAS_PAPEL_FORNECEDOR

	FROM 
		FORNECEDOR_PAPEL F
		INNER JOIN PAPEL P
			ON P.ID_FORNECEDOR_PAPEL = F.ID_FORNECEDOR_PAPEL
		INNER JOIN DETALHE_PEDIDO_PAPEL D
			ON D.ID_PAPEL = P.ID_PAPEL
	WHERE 
		F.NOME_FORNECEDOR NOT LIKE '%J'

	SELECT * FROM COMPRAS_PAPEL_FORNECEDOR
GO