USE MASTER 
DROP DATABASE IF EXISTS ARCO
GO
CREATE DATABASE ARCO
GO
 USE ARCO
CREATE TABLE FORNECEDOR_ARCO
(
ID_FORNECEDOR_ARCO  INT IDENTITY(1,1) PRIMARY KEY,
NOME_FORNECEDOR VARCHAR(MAX)
)
CREATE TABLE ARCO
(
ID_ARCO INT IDENTITY(1,1) PRIMARY KEY,
NOME_ARCO VARCHAR(200) UNIQUE,
CODIGO_ARCO VARCHAR(200)  ,
ID_FORNECEDOR_ARCO INT FOREIGN KEY REFERENCES FORNECEDOR_ARCO(ID_FORNECEDOR_ARCO)
)
CREATE TABLE CLIENTE_ARCO
(
ID_CLIENTE_ARCO INT IDENTITY(1,1) PRIMARY KEY,
NOME_CLIENTE_ARCO VARCHAR(200)
)
CREATE TABLE PEDIDO_ARCO
(
ID_PEDIDO_ARCO INT IDENTITY(1,1) PRIMARY KEY,
NUMERO_PEDIDO_ARCO INT  ,
QUANTIDADE_TOTAL INT,
VALOR_TOTAL DECIMAL(10,2),
DATA DATE,
ID_CLIENTE_ARCO INT FOREIGN KEY REFERENCES CLIENTE_ARCO(ID_CLIENTE_ARCO)
)
CREATE TABLE DETALHE_PEDIDO_ARCO
(
ID_DETALHE_PEDIDO_ARCO INT IDENTITY(1,1) PRIMARY KEY,
ID_ARCO  INT FOREIGN KEY REFERENCES ARCO(ID_ARCO),
QUANTIDADE INT,
VALOR DECIMAL(10,2),
ID_PEDIDO_ARCO INT FOREIGN KEY REFERENCES PEDIDO_ARCO(ID_PEDIDO_ARCO)
)
INSERT INTO FORNECEDOR_ARCO  VALUES 
('FORNECEDOR ARCO U'),('FORNECEDOR ARCO D')
INSERT INTO ARCO (NOME_ARCO,ID_FORNECEDOR_ARCO,CODIGO_ARCO) VALUES
('ARCO U',1,'U_ARCO'),('ARCO U2',1,'U2_ARCO'),('ARCO D',2,'D_ARCO'),('ARCO D2',2,'D2_ARCO')
,('ARCO ZY',2,'ZY_ARCO')
INSERT INTO CLIENTE_ARCO VALUES
('ARCO UD INC.') , ('DDU ARCO VENDAS SA')
INSERT INTO PEDIDO_ARCO 
(NUMERO_PEDIDO_ARCO,QUANTIDADE_TOTAL,VALOR_TOTAL,DATA,ID_CLIENTE_ARCO) VALUES
(100,2,1000,'2000-01-01',1),
(150,1,500,'2000-02-01',2),
(180,1,500,'2000-03-01',2),
(190,3,1500,'2000-04-01',2)
INSERT INTO DETALHE_PEDIDO_ARCO (ID_ARCO,QUANTIDADE,VALOR,ID_PEDIDO_ARCO) VALUES
(1,1,500,1),
(2,1,500,1),
(1,1,500,2),
(2,1,500,3), 
(3,1,500,4),
(4,2,1000,4)
 /*
 Ola Matheus Meza de Oliveira tudo bem com você? Preciso de uma ajuda aqui para entregar um relatório. Da uma força!
1 - Poderia selecionar o nome dos ARCOS e o nome do fornecedor dos ARCOS 
    onde o codigo do ARCO    começe com D, ordenados pelo nome do ARCO?
*/
/*
2 - Poderia selecionar o nome dos clientes a data do pedido do ARCO, quantidade e  valor
    onde a data do pedido é maior que 2000-03-01?
*/
/*
3 - Poderia criar uma tabela chamada [COMPRAS_ARCO] com os valores
o nome do ARCO, o nome do cliente, data da compra ?
*/

/*
4 - Poderia criar uma consulta, para buscar o NOME dos ARCOS que   tiveram nenhuma compra?
(PS: OBRIGATÓRIO TER UM JOIN ENTRE A TABELA ARCO E PEDIDO_ARCO, 
NADA DE SELECT * FROM ARCOS where NOME = XXX não!
*/
 /*
5 - Poderia criar uma tabela chamada [COMPRAS_ARCO_FORNECEDOR] com os valores
o nome do ARCO, quantidade do ARCO vendida, o valor e o nome do fornecedor onde o 
nome do fornecedor     termine com a letra U? */