USE MASTER 
DROP DATABASE IF EXISTS QUEIJO
GO
CREATE DATABASE QUEIJO
GO
 USE QUEIJO
CREATE TABLE FORNECEDOR_QUEIJO
(
ID_FORNECEDOR_QUEIJO  INT IDENTITY(1,1) PRIMARY KEY,
NOME_FORNECEDOR VARCHAR(MAX)
)
CREATE TABLE QUEIJO
(
ID_QUEIJO INT IDENTITY(1,1) PRIMARY KEY,
NOME_QUEIJO VARCHAR(200) UNIQUE,
CODIGO_QUEIJO VARCHAR(200)  ,
ID_FORNECEDOR_QUEIJO INT FOREIGN KEY REFERENCES FORNECEDOR_QUEIJO(ID_FORNECEDOR_QUEIJO)
)
CREATE TABLE CLIENTE_QUEIJO
(
ID_CLIENTE_QUEIJO INT IDENTITY(1,1) PRIMARY KEY,
NOME_CLIENTE_QUEIJO VARCHAR(200)
)
CREATE TABLE PEDIDO_QUEIJO
(
ID_PEDIDO_QUEIJO INT IDENTITY(1,1) PRIMARY KEY,
NUMERO_PEDIDO_QUEIJO INT  ,
QUANTIDADE_TOTAL INT,
VALOR_TOTAL DECIMAL(10,2),
DATA DATE,
ID_CLIENTE_QUEIJO INT FOREIGN KEY REFERENCES CLIENTE_QUEIJO(ID_CLIENTE_QUEIJO)
)
CREATE TABLE DETALHE_PEDIDO_QUEIJO
(
ID_DETALHE_PEDIDO_QUEIJO INT IDENTITY(1,1) PRIMARY KEY,
ID_QUEIJO  INT FOREIGN KEY REFERENCES QUEIJO(ID_QUEIJO),
QUANTIDADE INT,
VALOR DECIMAL(10,2),
ID_PEDIDO_QUEIJO INT FOREIGN KEY REFERENCES PEDIDO_QUEIJO(ID_PEDIDO_QUEIJO)
)
INSERT INTO FORNECEDOR_QUEIJO  VALUES 
('FORNECEDOR QUEIJO N'),('FORNECEDOR QUEIJO K')
INSERT INTO QUEIJO (NOME_QUEIJO,ID_FORNECEDOR_QUEIJO,CODIGO_QUEIJO) VALUES
('QUEIJO N',1,'N_QUEIJO'),('QUEIJO N2',1,'N2_QUEIJO'),('QUEIJO K',2,'K_QUEIJO'),('QUEIJO K2',2,'K2_QUEIJO')
,('QUEIJO ZY',2,'ZY_QUEIJO')
INSERT INTO CLIENTE_QUEIJO VALUES
('QUEIJO NK INC.') , ('KKN QUEIJO VENDAS SA')
INSERT INTO PEDIDO_QUEIJO 
(NUMERO_PEDIDO_QUEIJO,QUANTIDADE_TOTAL,VALOR_TOTAL,DATA,ID_CLIENTE_QUEIJO) VALUES
(100,2,1000,'2000-01-01',1),
(150,1,500,'2000-02-01',2),
(180,1,500,'2000-03-01',2),
(190,3,1500,'2000-04-01',2)
INSERT INTO DETALHE_PEDIDO_QUEIJO (ID_QUEIJO,QUANTIDADE,VALOR,ID_PEDIDO_QUEIJO) VALUES
(1,1,500,1),
(2,1,500,1),
(1,1,500,2),
(2,1,500,3), 
(3,1,500,4),
(4,2,1000,4)
 /*
 Ola James Leite Francisco tudo bem com você? Preciso de uma ajuda aqui para entregar um relatório. Da uma força!
1 - Poderia selecionar o nome dos QUEIJOS e o nome do fornecedor dos QUEIJOS 
    onde o codigo do QUEIJO não  começe com K, ordenados pelo nome do QUEIJO?
*/
/*
2 - Poderia selecionar o nome dos clientes a data do pedido do QUEIJO, quantidade e  valor
    onde a data do pedido é maior que 2000-03-01?
*/
/*
3 - Poderia criar uma tabela chamada [COMPRAS_QUEIJO] com os valores
o nome do QUEIJO, o nome do cliente, data da compra ?
*/

/*
4 - Poderia criar uma consulta, para buscar o NOME dos QUEIJOS que não tiveram nenhuma compra?
(PS: OBRIGATÓRIO TER UM JOIN ENTRE A TABELA QUEIJO E PEDIDO_QUEIJO, 
NADA DE SELECT * FROM QUEIJOS where NOME = XXX não!
*/
 /*
5 - Poderia criar uma tabela chamada [COMPRAS_QUEIJO_FORNECEDOR] com os valores
o nome do QUEIJO, quantidade do QUEIJO vendida, o valor e o nome do fornecedor onde o 
nome do fornecedor não   termine com a letra N? */