USE MASTER 
DROP DATABASE IF EXISTS PEIXE
GO
CREATE DATABASE PEIXE
GO
 USE PEIXE
CREATE TABLE FORNECEDOR_PEIXE
(
ID_FORNECEDOR_PEIXE  INT IDENTITY(1,1) PRIMARY KEY,
NOME_FORNECEDOR VARCHAR(MAX)
)
CREATE TABLE PEIXE
(
ID_PEIXE INT IDENTITY(1,1) PRIMARY KEY,
NOME_PEIXE VARCHAR(200) UNIQUE,
CODIGO_PEIXE VARCHAR(200)  ,
ID_FORNECEDOR_PEIXE INT FOREIGN KEY REFERENCES FORNECEDOR_PEIXE(ID_FORNECEDOR_PEIXE)
)
CREATE TABLE CLIENTE_PEIXE
(
ID_CLIENTE_PEIXE INT IDENTITY(1,1) PRIMARY KEY,
NOME_CLIENTE_PEIXE VARCHAR(200)
)
CREATE TABLE PEDIDO_PEIXE
(
ID_PEDIDO_PEIXE INT IDENTITY(1,1) PRIMARY KEY,
NUMERO_PEDIDO_PEIXE INT  ,
QUANTIDADE_TOTAL INT,
VALOR_TOTAL DECIMAL(10,2),
DATA DATE,
ID_CLIENTE_PEIXE INT FOREIGN KEY REFERENCES CLIENTE_PEIXE(ID_CLIENTE_PEIXE)
)
CREATE TABLE DETALHE_PEDIDO_PEIXE
(
ID_DETALHE_PEDIDO_PEIXE INT IDENTITY(1,1) PRIMARY KEY,
ID_PEIXE  INT FOREIGN KEY REFERENCES PEIXE(ID_PEIXE),
QUANTIDADE INT,
VALOR DECIMAL(10,2),
ID_PEDIDO_PEIXE INT FOREIGN KEY REFERENCES PEDIDO_PEIXE(ID_PEDIDO_PEIXE)
)
INSERT INTO FORNECEDOR_PEIXE  VALUES 
('FORNECEDOR PEIXE G'),('FORNECEDOR PEIXE R')
INSERT INTO PEIXE (NOME_PEIXE,ID_FORNECEDOR_PEIXE,CODIGO_PEIXE) VALUES
('PEIXE G',1,'G_PEIXE'),('PEIXE G2',1,'G2_PEIXE'),('PEIXE R',2,'R_PEIXE'),('PEIXE R2',2,'R2_PEIXE')
,('PEIXE ZY',2,'ZY_PEIXE')
INSERT INTO CLIENTE_PEIXE VALUES
('PEIXE GR INC.') , ('RRG PEIXE VENDAS SA')
INSERT INTO PEDIDO_PEIXE 
(NUMERO_PEDIDO_PEIXE,QUANTIDADE_TOTAL,VALOR_TOTAL,DATA,ID_CLIENTE_PEIXE) VALUES
(100,2,1000,'2000-01-01',1),
(150,1,500,'2000-02-01',2),
(180,1,500,'2000-03-01',2),
(190,3,1500,'2000-04-01',2)
INSERT INTO DETALHE_PEDIDO_PEIXE (ID_PEIXE,QUANTIDADE,VALOR,ID_PEDIDO_PEIXE) VALUES
(1,1,500,1),
(2,1,500,1),
(1,1,500,2),
(2,1,500,3), 
(3,1,500,4),
(4,2,1000,4)
 /*
 Ola Edmilton Oliveira da Mota tudo bem com você? Preciso de uma ajuda aqui para entregar um relatório. Da uma força!
1 - Poderia selecionar o nome dos PEIXES e o nome do fornecedor dos PEIXES 
    onde o codigo do PEIXE    começe com R, ordenados pelo nome do PEIXE?
*/
/*
2 - Poderia selecionar o nome dos clientes a data do pedido do PEIXE, quantidade e  valor
    onde a data do pedido é maior que 2000-03-01?
*/
/*
3 - Poderia criar uma tabela chamada [COMPRAS_PEIXE] com os valores
o nome do PEIXE, o nome do cliente, data da compra ?
*/

/*
4 - Poderia criar uma consulta, para buscar o NOME dos PEIXES que   tiveram nenhuma compra?
(PS: OBRIGATÓRIO TER UM JOIN ENTRE A TABELA PEIXE E PEDIDO_PEIXE, 
NADA DE SELECT * FROM PEIXES where NOME = XXX não!
*/
 /*
5 - Poderia criar uma tabela chamada [COMPRAS_PEIXE_FORNECEDOR] com os valores
o nome do PEIXE, quantidade do PEIXE vendida, o valor e o nome do fornecedor onde o 
nome do fornecedor     termine com a letra G? */