USE MASTER 
DROP DATABASE IF EXISTS CACTO
GO
CREATE DATABASE CACTO
GO
 USE CACTO
CREATE TABLE FORNECEDOR_CACTO
(
ID_FORNECEDOR_CACTO  INT IDENTITY(1,1) PRIMARY KEY,
NOME_FORNECEDOR VARCHAR(MAX)
)
CREATE TABLE CACTO
(
ID_CACTO INT IDENTITY(1,1) PRIMARY KEY,
NOME_CACTO VARCHAR(200) UNIQUE,
CODIGO_CACTO VARCHAR(200)  ,
ID_FORNECEDOR_CACTO INT FOREIGN KEY REFERENCES FORNECEDOR_CACTO(ID_FORNECEDOR_CACTO)
)
CREATE TABLE CLIENTE_CACTO
(
ID_CLIENTE_CACTO INT IDENTITY(1,1) PRIMARY KEY,
NOME_CLIENTE_CACTO VARCHAR(200)
)
CREATE TABLE PEDIDO_CACTO
(
ID_PEDIDO_CACTO INT IDENTITY(1,1) PRIMARY KEY,
NUMERO_PEDIDO_CACTO INT  ,
QUANTIDADE_TOTAL INT,
VALOR_TOTAL DECIMAL(10,2),
DATA DATE,
ID_CLIENTE_CACTO INT FOREIGN KEY REFERENCES CLIENTE_CACTO(ID_CLIENTE_CACTO)
)
CREATE TABLE DETALHE_PEDIDO_CACTO
(
ID_DETALHE_PEDIDO_CACTO INT IDENTITY(1,1) PRIMARY KEY,
ID_CACTO  INT FOREIGN KEY REFERENCES CACTO(ID_CACTO),
QUANTIDADE INT,
VALOR DECIMAL(10,2),
ID_PEDIDO_CACTO INT FOREIGN KEY REFERENCES PEDIDO_CACTO(ID_PEDIDO_CACTO)
)
INSERT INTO FORNECEDOR_CACTO  VALUES 
('FORNECEDOR CACTO X'),('FORNECEDOR CACTO Z')
INSERT INTO CACTO (NOME_CACTO,ID_FORNECEDOR_CACTO,CODIGO_CACTO) VALUES
('CACTO X',1,'X_CACTO'),('CACTO X2',1,'X2_CACTO'),('CACTO Z',2,'Z_CACTO'),('CACTO Z2',2,'Z2_CACTO')
,('CACTO ZY',2,'ZY_CACTO')
INSERT INTO CLIENTE_CACTO VALUES
('CACTO XZ INC.') , ('ZZX CACTO VENDAS SA')
INSERT INTO PEDIDO_CACTO 
(NUMERO_PEDIDO_CACTO,QUANTIDADE_TOTAL,VALOR_TOTAL,DATA,ID_CLIENTE_CACTO) VALUES
(100,2,1000,'2000-01-01',1),
(150,1,500,'2000-02-01',2),
(180,1,500,'2000-03-01',2),
(190,3,1500,'2000-04-01',2)
INSERT INTO DETALHE_PEDIDO_CACTO (ID_CACTO,QUANTIDADE,VALOR,ID_PEDIDO_CACTO) VALUES
(1,1,500,1),
(2,1,500,1),
(1,1,500,2),
(2,1,500,3), 
(3,1,500,4),
(4,2,1000,4)
 /*
 Ola Murilo Alberto dos Santos tudo bem com você? Preciso de uma ajuda aqui para entregar um relatório. Da uma força!
1 - Poderia selecionar o nome dos CACTOS e o nome do fornecedor dos CACTOS 
    onde o codigo do CACTO não  começe com Z, ordenados pelo nome do CACTO?
*/
/*
2 - Poderia selecionar o nome dos clientes a data do pedido do CACTO, quantidade e  valor
    onde a data do pedido é maior que 2000-03-01?
*/
/*
3 - Poderia criar uma tabela chamada [COMPRAS_CACTO] com os valores
o nome do CACTO, o nome do cliente, data da compra ?
*/

/*
4 - Poderia criar uma consulta, para buscar o NOME dos CACTOS que não tiveram nenhuma compra?
(PS: OBRIGATÓRIO TER UM JOIN ENTRE A TABELA CACTO E PEDIDO_CACTO, 
NADA DE SELECT * FROM CACTOS where NOME = XXX não!
*/
 /*
5 - Poderia criar uma tabela chamada [COMPRAS_CACTO_FORNECEDOR] com os valores
o nome do CACTO, quantidade do CACTO vendida, o valor e o nome do fornecedor onde o 
nome do fornecedor não   termine com a letra X? */