USE MASTER 
DROP DATABASE IF EXISTS SABAO
GO
CREATE DATABASE SABAO
GO
 USE SABAO
CREATE TABLE FORNECEDOR_SABAO
(
ID_FORNECEDOR_SABAO  INT IDENTITY(1,1) PRIMARY KEY,
NOME_FORNECEDOR VARCHAR(MAX)
)
CREATE TABLE SABAO
(
ID_SABAO INT IDENTITY(1,1) PRIMARY KEY,
NOME_SABAO VARCHAR(200) UNIQUE,
CODIGO_SABAO VARCHAR(200)  ,
ID_FORNECEDOR_SABAO INT FOREIGN KEY REFERENCES FORNECEDOR_SABAO(ID_FORNECEDOR_SABAO)
)
CREATE TABLE CLIENTE_SABAO
(
ID_CLIENTE_SABAO INT IDENTITY(1,1) PRIMARY KEY,
NOME_CLIENTE_SABAO VARCHAR(200)
)
CREATE TABLE PEDIDO_SABAO
(
ID_PEDIDO_SABAO INT IDENTITY(1,1) PRIMARY KEY,
NUMERO_PEDIDO_SABAO INT  ,
QUANTIDADE_TOTAL INT,
VALOR_TOTAL DECIMAL(10,2),
DATA DATE,
ID_CLIENTE_SABAO INT FOREIGN KEY REFERENCES CLIENTE_SABAO(ID_CLIENTE_SABAO)
)
CREATE TABLE DETALHE_PEDIDO_SABAO
(
ID_DETALHE_PEDIDO_SABAO INT IDENTITY(1,1) PRIMARY KEY,
ID_SABAO  INT FOREIGN KEY REFERENCES SABAO(ID_SABAO),
QUANTIDADE INT,
VALOR DECIMAL(10,2),
ID_PEDIDO_SABAO INT FOREIGN KEY REFERENCES PEDIDO_SABAO(ID_PEDIDO_SABAO)
)
INSERT INTO FORNECEDOR_SABAO  VALUES 
('FORNECEDOR SABAO L'),('FORNECEDOR SABAO M')
INSERT INTO SABAO (NOME_SABAO,ID_FORNECEDOR_SABAO,CODIGO_SABAO) VALUES
('SABAO L',1,'L_SABAO'),('SABAO L2',1,'L2_SABAO'),('SABAO M',2,'M_SABAO'),('SABAO M2',2,'M2_SABAO')
,('SABAO ZY',2,'ZY_SABAO')
INSERT INTO CLIENTE_SABAO VALUES
('SABAO LM INC.') , ('MML SABAO VENDAS SA')
INSERT INTO PEDIDO_SABAO 
(NUMERO_PEDIDO_SABAO,QUANTIDADE_TOTAL,VALOR_TOTAL,DATA,ID_CLIENTE_SABAO) VALUES
(100,2,1000,'2000-01-01',1),
(150,1,500,'2000-02-01',2),
(180,1,500,'2000-03-01',2),
(190,3,1500,'2000-04-01',2)
INSERT INTO DETALHE_PEDIDO_SABAO (ID_SABAO,QUANTIDADE,VALOR,ID_PEDIDO_SABAO) VALUES
(1,1,500,1),
(2,1,500,1),
(1,1,500,2),
(2,1,500,3), 
(3,1,500,4),
(4,2,1000,4)
 /*
 Ola Ingrid Tamara Dutra Contreras tudo bem com você? Preciso de uma ajuda aqui para entregar um relatório. Da uma força!
1 - Poderia selecionar o nome dos SABAOS e o nome do fornecedor dos SABAOS 
    onde o codigo do SABAO não  começe com M, ordenados pelo nome do SABAO?
*/
/*
2 - Poderia selecionar o nome dos clientes a data do pedido do SABAO, quantidade e  valor
    onde a data do pedido é maior que 2000-03-01?
*/
/*
3 - Poderia criar uma tabela chamada [COMPRAS_SABAO] com os valores
o nome do SABAO, o nome do cliente, data da compra ?
*/

/*
4 - Poderia criar uma consulta, para buscar o NOME dos SABAOS que não tiveram nenhuma compra?
(PS: OBRIGATÓRIO TER UM JOIN ENTRE A TABELA SABAO E PEDIDO_SABAO, 
NADA DE SELECT * FROM SABAOS where NOME = XXX não!
*/
 /*
5 - Poderia criar uma tabela chamada [COMPRAS_SABAO_FORNECEDOR] com os valores
o nome do SABAO, quantidade do SABAO vendida, o valor e o nome do fornecedor onde o 
nome do fornecedor não   termine com a letra L? */