USE MASTER 
DROP DATABASE IF EXISTS CIGARRO
GO
CREATE DATABASE CIGARRO
GO
 USE CIGARRO
CREATE TABLE FORNECEDOR_CIGARRO
(
ID_FORNECEDOR_CIGARRO  INT IDENTITY(1,1) PRIMARY KEY,
NOME_FORNECEDOR VARCHAR(MAX)
)
CREATE TABLE CIGARRO
(
ID_CIGARRO INT IDENTITY(1,1) PRIMARY KEY,
NOME_CIGARRO VARCHAR(200) UNIQUE,
CODIGO_CIGARRO VARCHAR(200)  ,
ID_FORNECEDOR_CIGARRO INT FOREIGN KEY REFERENCES FORNECEDOR_CIGARRO(ID_FORNECEDOR_CIGARRO)
)
CREATE TABLE CLIENTE_CIGARRO
(
ID_CLIENTE_CIGARRO INT IDENTITY(1,1) PRIMARY KEY,
NOME_CLIENTE_CIGARRO VARCHAR(200)
)
CREATE TABLE PEDIDO_CIGARRO
(
ID_PEDIDO_CIGARRO INT IDENTITY(1,1) PRIMARY KEY,
NUMERO_PEDIDO_CIGARRO INT  ,
QUANTIDADE_TOTAL INT,
VALOR_TOTAL DECIMAL(10,2),
DATA DATE,
ID_CLIENTE_CIGARRO INT FOREIGN KEY REFERENCES CLIENTE_CIGARRO(ID_CLIENTE_CIGARRO)
)
CREATE TABLE DETALHE_PEDIDO_CIGARRO
(
ID_DETALHE_PEDIDO_CIGARRO INT IDENTITY(1,1) PRIMARY KEY,
ID_CIGARRO  INT FOREIGN KEY REFERENCES CIGARRO(ID_CIGARRO),
QUANTIDADE INT,
VALOR DECIMAL(10,2),
ID_PEDIDO_CIGARRO INT FOREIGN KEY REFERENCES PEDIDO_CIGARRO(ID_PEDIDO_CIGARRO)
)
INSERT INTO FORNECEDOR_CIGARRO  VALUES 
('FORNECEDOR CIGARRO H'),('FORNECEDOR CIGARRO Q')
INSERT INTO CIGARRO (NOME_CIGARRO,ID_FORNECEDOR_CIGARRO,CODIGO_CIGARRO) VALUES
('CIGARRO H',1,'H_CIGARRO'),('CIGARRO H2',1,'H2_CIGARRO'),('CIGARRO Q',2,'Q_CIGARRO'),('CIGARRO Q2',2,'Q2_CIGARRO')
,('CIGARRO ZY',2,'ZY_CIGARRO')
INSERT INTO CLIENTE_CIGARRO VALUES
('CIGARRO HQ INC.') , ('QQH CIGARRO VENDAS SA')
INSERT INTO PEDIDO_CIGARRO 
(NUMERO_PEDIDO_CIGARRO,QUANTIDADE_TOTAL,VALOR_TOTAL,DATA,ID_CLIENTE_CIGARRO) VALUES
(100,2,1000,'2000-01-01',1),
(150,1,500,'2000-02-01',2),
(180,1,500,'2000-03-01',2),
(190,3,1500,'2000-04-01',2)
INSERT INTO DETALHE_PEDIDO_CIGARRO (ID_CIGARRO,QUANTIDADE,VALOR,ID_PEDIDO_CIGARRO) VALUES
(1,1,500,1),
(2,1,500,1),
(1,1,500,2),
(2,1,500,3), 
(3,1,500,4),
(4,2,1000,4)
 /*
 Ola Fabio de Arruda Oliveira tudo bem com você? Preciso de uma ajuda aqui para entregar um relatório. Da uma força!
1 - Poderia selecionar o nome dos CIGARROS e o nome do fornecedor dos CIGARROS 
    onde o codigo do CIGARRO não  começe com Q, ordenados pelo nome do CIGARRO?
*/
/*
2 - Poderia selecionar o nome dos clientes a data do pedido do CIGARRO, quantidade e  valor
    onde a data do pedido é maior que 2000-03-01?
*/
/*
3 - Poderia criar uma tabela chamada [COMPRAS_CIGARRO] com os valores
o nome do CIGARRO, o nome do cliente, data da compra ?
*/

/*
4 - Poderia criar uma consulta, para buscar o NOME dos CIGARROS que não tiveram nenhuma compra?
(PS: OBRIGATÓRIO TER UM JOIN ENTRE A TABELA CIGARRO E PEDIDO_CIGARRO, 
NADA DE SELECT * FROM CIGARROS where NOME = XXX não!
*/
 /*
5 - Poderia criar uma tabela chamada [COMPRAS_CIGARRO_FORNECEDOR] com os valores
o nome do CIGARRO, quantidade do CIGARRO vendida, o valor e o nome do fornecedor onde o 
nome do fornecedor não   termine com a letra H? */