USE MASTER 
DROP DATABASE IF EXISTS FONE
GO
CREATE DATABASE FONE
GO
 USE FONE
CREATE TABLE FORNECEDOR_FONE
(
ID_FORNECEDOR_FONE  INT IDENTITY(1,1) PRIMARY KEY,
NOME_FORNECEDOR VARCHAR(MAX)
)
CREATE TABLE FONE
(
ID_FONE INT IDENTITY(1,1) PRIMARY KEY,
NOME_FONE VARCHAR(200) UNIQUE,
CODIGO_FONE VARCHAR(200)  ,
ID_FORNECEDOR_FONE INT FOREIGN KEY REFERENCES FORNECEDOR_FONE(ID_FORNECEDOR_FONE)
)
CREATE TABLE CLIENTE_FONE
(
ID_CLIENTE_FONE INT IDENTITY(1,1) PRIMARY KEY,
NOME_CLIENTE_FONE VARCHAR(200)
)
CREATE TABLE PEDIDO_FONE
(
ID_PEDIDO_FONE INT IDENTITY(1,1) PRIMARY KEY,
NUMERO_PEDIDO_FONE INT  ,
QUANTIDADE_TOTAL INT,
VALOR_TOTAL DECIMAL(10,2),
DATA DATE,
ID_CLIENTE_FONE INT FOREIGN KEY REFERENCES CLIENTE_FONE(ID_CLIENTE_FONE)
)
CREATE TABLE DETALHE_PEDIDO_FONE
(
ID_DETALHE_PEDIDO_FONE INT IDENTITY(1,1) PRIMARY KEY,
ID_FONE  INT FOREIGN KEY REFERENCES FONE(ID_FONE),
QUANTIDADE INT,
VALOR DECIMAL(10,2),
ID_PEDIDO_FONE INT FOREIGN KEY REFERENCES PEDIDO_FONE(ID_PEDIDO_FONE)
)
INSERT INTO FORNECEDOR_FONE  VALUES 
('FORNECEDOR FONE C'),('FORNECEDOR FONE B')
INSERT INTO FONE (NOME_FONE,ID_FORNECEDOR_FONE,CODIGO_FONE) VALUES
('FONE C',1,'C_FONE'),('FONE C2',1,'C2_FONE'),('FONE B',2,'B_FONE'),('FONE B2',2,'B2_FONE')
,('FONE ZY',2,'ZY_FONE')
INSERT INTO CLIENTE_FONE VALUES
('FONE CB INC.') , ('BBC FONE VENDAS SA')
INSERT INTO PEDIDO_FONE 
(NUMERO_PEDIDO_FONE,QUANTIDADE_TOTAL,VALOR_TOTAL,DATA,ID_CLIENTE_FONE) VALUES
(100,2,1000,'2000-01-01',1),
(150,1,500,'2000-02-01',2),
(180,1,500,'2000-03-01',2),
(190,3,1500,'2000-04-01',2)
INSERT INTO DETALHE_PEDIDO_FONE (ID_FONE,QUANTIDADE,VALOR,ID_PEDIDO_FONE) VALUES
(1,1,500,1),
(2,1,500,1),
(1,1,500,2),
(2,1,500,3), 
(3,1,500,4),
(4,2,1000,4)
 /*
 Ola Cesar Henrique Moreno de Almeida tudo bem com você? Preciso de uma ajuda aqui para entregar um relatório. Da uma força!
1 - Poderia selecionar o nome dos FONES e o nome do fornecedor dos FONES 
    onde o codigo do FONE    começe com B, ordenados pelo nome do FONE?
*/
/*
2 - Poderia selecionar o nome dos clientes a data do pedido do FONE, quantidade e  valor
    onde a data do pedido é maior que 2000-03-01?
*/
/*
3 - Poderia criar uma tabela chamada [COMPRAS_FONE] com os valores
o nome do FONE, o nome do cliente, data da compra ?
*/

/*
4 - Poderia criar uma consulta, para buscar o NOME dos FONES que   tiveram nenhuma compra?
(PS: OBRIGATÓRIO TER UM JOIN ENTRE A TABELA FONE E PEDIDO_FONE, 
NADA DE SELECT * FROM FONES where NOME = XXX não!
*/
 /*
5 - Poderia criar uma tabela chamada [COMPRAS_FONE_FORNECEDOR] com os valores
o nome do FONE, quantidade do FONE vendida, o valor e o nome do fornecedor onde o 
nome do fornecedor     termine com a letra C? */