USE MASTER 
DROP DATABASE IF EXISTS LAPIS
GO
CREATE DATABASE LAPIS
GO
 USE LAPIS
CREATE TABLE FORNECEDOR_LAPIS
(
ID_FORNECEDOR_LAPIS  INT IDENTITY(1,1) PRIMARY KEY,
NOME_FORNECEDOR VARCHAR(MAX)
)
CREATE TABLE LAPIS
(
ID_LAPIS INT IDENTITY(1,1) PRIMARY KEY,
NOME_LAPIS VARCHAR(200) UNIQUE,
CODIGO_LAPIS VARCHAR(200)  ,
ID_FORNECEDOR_LAPIS INT FOREIGN KEY REFERENCES FORNECEDOR_LAPIS(ID_FORNECEDOR_LAPIS)
)
CREATE TABLE CLIENTE_LAPIS
(
ID_CLIENTE_LAPIS INT IDENTITY(1,1) PRIMARY KEY,
NOME_CLIENTE_LAPIS VARCHAR(200)
)
CREATE TABLE PEDIDO_LAPIS
(
ID_PEDIDO_LAPIS INT IDENTITY(1,1) PRIMARY KEY,
NUMERO_PEDIDO_LAPIS INT  ,
QUANTIDADE_TOTAL INT,
VALOR_TOTAL DECIMAL(10,2),
DATA DATE,
ID_CLIENTE_LAPIS INT FOREIGN KEY REFERENCES CLIENTE_LAPIS(ID_CLIENTE_LAPIS)
)
CREATE TABLE DETALHE_PEDIDO_LAPIS
(
ID_DETALHE_PEDIDO_LAPIS INT IDENTITY(1,1) PRIMARY KEY,
ID_LAPIS  INT FOREIGN KEY REFERENCES LAPIS(ID_LAPIS),
QUANTIDADE INT,
VALOR DECIMAL(10,2),
ID_PEDIDO_LAPIS INT FOREIGN KEY REFERENCES PEDIDO_LAPIS(ID_PEDIDO_LAPIS)
)
INSERT INTO FORNECEDOR_LAPIS  VALUES 
('FORNECEDOR LAPIS E'),('FORNECEDOR LAPIS T')
INSERT INTO LAPIS (NOME_LAPIS,ID_FORNECEDOR_LAPIS,CODIGO_LAPIS) VALUES
('LAPIS E',1,'E_LAPIS'),('LAPIS E2',1,'E2_LAPIS'),('LAPIS T',2,'T_LAPIS'),('LAPIS T2',2,'T2_LAPIS')
,('LAPIS ZY',2,'ZY_LAPIS')
INSERT INTO CLIENTE_LAPIS VALUES
('LAPIS ET INC.') , ('TTE LAPIS VENDAS SA')
INSERT INTO PEDIDO_LAPIS 
(NUMERO_PEDIDO_LAPIS,QUANTIDADE_TOTAL,VALOR_TOTAL,DATA,ID_CLIENTE_LAPIS) VALUES
(100,2,1000,'2000-01-01',1),
(150,1,500,'2000-02-01',2),
(180,1,500,'2000-03-01',2),
(190,3,1500,'2000-04-01',2)
INSERT INTO DETALHE_PEDIDO_LAPIS (ID_LAPIS,QUANTIDADE,VALOR,ID_PEDIDO_LAPIS) VALUES
(1,1,500,1),
(2,1,500,1),
(1,1,500,2),
(2,1,500,3), 
(3,1,500,4),
(4,2,1000,4)
 /*
 Ola Cleber Carvalho de Andrade tudo bem com você? Preciso de uma ajuda aqui para entregar um relatório. Da uma força!
1 - Poderia selecionar o nome dos LAPISS e o nome do fornecedor dos LAPISS 
    onde o codigo do LAPIS    começe com T, ordenados pelo nome do LAPIS?
*/
/*
2 - Poderia selecionar o nome dos clientes a data do pedido do LAPIS, quantidade e  valor
    onde a data do pedido é maior que 2000-03-01?
*/
/*
3 - Poderia criar uma tabela chamada [COMPRAS_LAPIS] com os valores
o nome do LAPIS, o nome do cliente, data da compra ?
*/

/*
4 - Poderia criar uma consulta, para buscar o NOME dos LAPISS que   tiveram nenhuma compra?
(PS: OBRIGATÓRIO TER UM JOIN ENTRE A TABELA LAPIS E PEDIDO_LAPIS, 
NADA DE SELECT * FROM LAPISS where NOME = XXX não!
*/
 /*
5 - Poderia criar uma tabela chamada [COMPRAS_LAPIS_FORNECEDOR] com os valores
o nome do LAPIS, quantidade do LAPIS vendida, o valor e o nome do fornecedor onde o 
nome do fornecedor     termine com a letra E? */