USE MASTER 
DROP DATABASE IF EXISTS VIDEO_GAME
GO
CREATE DATABASE VIDEO_GAME
GO
 USE VIDEO_GAME
CREATE TABLE FORNECEDOR_VIDEO_GAME
(
ID_FORNECEDOR_VIDEO_GAME  INT IDENTITY(1,1) PRIMARY KEY,
NOME_FORNECEDOR VARCHAR(MAX)
)
CREATE TABLE VIDEO_GAME
(
ID_VIDEO_GAME INT IDENTITY(1,1) PRIMARY KEY,
NOME_VIDEO_GAME VARCHAR(200) UNIQUE,
CODIGO_VIDEO_GAME VARCHAR(200)  ,
ID_FORNECEDOR_VIDEO_GAME INT FOREIGN KEY REFERENCES FORNECEDOR_VIDEO_GAME(ID_FORNECEDOR_VIDEO_GAME)
)
CREATE TABLE CLIENTE_VIDEO_GAME
(
ID_CLIENTE_VIDEO_GAME INT IDENTITY(1,1) PRIMARY KEY,
NOME_CLIENTE_VIDEO_GAME VARCHAR(200)
)
CREATE TABLE PEDIDO_VIDEO_GAME
(
ID_PEDIDO_VIDEO_GAME INT IDENTITY(1,1) PRIMARY KEY,
NUMERO_PEDIDO_VIDEO_GAME INT  ,
QUANTIDADE_TOTAL INT,
VALOR_TOTAL DECIMAL(10,2),
DATA DATE,
ID_CLIENTE_VIDEO_GAME INT FOREIGN KEY REFERENCES CLIENTE_VIDEO_GAME(ID_CLIENTE_VIDEO_GAME)
)
CREATE TABLE DETALHE_PEDIDO_VIDEO_GAME
(
ID_DETALHE_PEDIDO_VIDEO_GAME INT IDENTITY(1,1) PRIMARY KEY,
ID_VIDEO_GAME  INT FOREIGN KEY REFERENCES VIDEO_GAME(ID_VIDEO_GAME),
QUANTIDADE INT,
VALOR DECIMAL(10,2),
ID_PEDIDO_VIDEO_GAME INT FOREIGN KEY REFERENCES PEDIDO_VIDEO_GAME(ID_PEDIDO_VIDEO_GAME)
)
INSERT INTO FORNECEDOR_VIDEO_GAME  VALUES 
('FORNECEDOR VIDEO_GAME C'),('FORNECEDOR VIDEO_GAME V')
INSERT INTO VIDEO_GAME (NOME_VIDEO_GAME,ID_FORNECEDOR_VIDEO_GAME,CODIGO_VIDEO_GAME) VALUES
('VIDEO_GAME C',1,'C_VIDEO_GAME'),('VIDEO_GAME C2',1,'C2_VIDEO_GAME'),('VIDEO_GAME V',2,'V_VIDEO_GAME'),('VIDEO_GAME V2',2,'V2_VIDEO_GAME')
,('VIDEO_GAME ZY',2,'ZY_VIDEO_GAME')
INSERT INTO CLIENTE_VIDEO_GAME VALUES
('VIDEO_GAME CV INC.') , ('VVC VIDEO_GAME VENDAS SA')
INSERT INTO PEDIDO_VIDEO_GAME 
(NUMERO_PEDIDO_VIDEO_GAME,QUANTIDADE_TOTAL,VALOR_TOTAL,DATA,ID_CLIENTE_VIDEO_GAME) VALUES
(100,2,1000,'2000-01-01',1),
(150,1,500,'2000-02-01',2),
(180,1,500,'2000-03-01',2),
(190,3,1500,'2000-04-01',2)
INSERT INTO DETALHE_PEDIDO_VIDEO_GAME (ID_VIDEO_GAME,QUANTIDADE,VALOR,ID_PEDIDO_VIDEO_GAME) VALUES
(1,1,500,1),
(2,1,500,1),
(1,1,500,2),
(2,1,500,3), 
(3,1,500,4),
(4,2,1000,4)
 /*
 Ola Ricardo Alexandre Pavão Junior tudo bem com você? Preciso de uma ajuda aqui para entregar um relatório. Da uma força!
1 - Poderia selecionar o nome dos VIDEO_GAMES e o nome do fornecedor dos VIDEO_GAMES 
    onde o codigo do VIDEO_GAME não  começe com V, ordenados pelo nome do VIDEO_GAME?
*/
/*
2 - Poderia selecionar o nome dos clientes a data do pedido do VIDEO_GAME, quantidade e  valor
    onde a data do pedido é maior que 2000-03-01?
*/
/*
3 - Poderia criar uma tabela chamada [COMPRAS_VIDEO_GAME] com os valores
o nome do VIDEO_GAME, o nome do cliente, data da compra ?
*/

/*
4 - Poderia criar uma consulta, para buscar o NOME dos VIDEO_GAMES que não tiveram nenhuma compra?
(PS: OBRIGATÓRIO TER UM JOIN ENTRE A TABELA VIDEO_GAME E PEDIDO_VIDEO_GAME, 
NADA DE SELECT * FROM VIDEO_GAMES where NOME = XXX não!
*/
 /*
5 - Poderia criar uma tabela chamada [COMPRAS_VIDEO_GAME_FORNECEDOR] com os valores
o nome do VIDEO_GAME, quantidade do VIDEO_GAME vendida, o valor e o nome do fornecedor onde o 
nome do fornecedor não   termine com a letra C? */