USE MASTER 
DROP DATABASE IF EXISTS CAVALO
GO
CREATE DATABASE CAVALO
GO
 USE CAVALO
CREATE TABLE FORNECEDOR_CAVALO
(
ID_FORNECEDOR_CAVALO  INT IDENTITY(1,1) PRIMARY KEY,
NOME_FORNECEDOR VARCHAR(MAX)
)
CREATE TABLE CAVALO
(
ID_CAVALO INT IDENTITY(1,1) PRIMARY KEY,
NOME_CAVALO VARCHAR(200) UNIQUE,
CODIGO_CAVALO VARCHAR(200)  ,
ID_FORNECEDOR_CAVALO INT FOREIGN KEY REFERENCES FORNECEDOR_CAVALO(ID_FORNECEDOR_CAVALO)
)
CREATE TABLE CLIENTE_CAVALO
(
ID_CLIENTE_CAVALO INT IDENTITY(1,1) PRIMARY KEY,
NOME_CLIENTE_CAVALO VARCHAR(200)
)
CREATE TABLE PEDIDO_CAVALO
(
ID_PEDIDO_CAVALO INT IDENTITY(1,1) PRIMARY KEY,
NUMERO_PEDIDO_CAVALO INT  ,
QUANTIDADE_TOTAL INT,
VALOR_TOTAL DECIMAL(10,2),
DATA DATE,
ID_CLIENTE_CAVALO INT FOREIGN KEY REFERENCES CLIENTE_CAVALO(ID_CLIENTE_CAVALO)
)
CREATE TABLE DETALHE_PEDIDO_CAVALO
(
ID_DETALHE_PEDIDO_CAVALO INT IDENTITY(1,1) PRIMARY KEY,
ID_CAVALO  INT FOREIGN KEY REFERENCES CAVALO(ID_CAVALO),
QUANTIDADE INT,
VALOR DECIMAL(10,2),
ID_PEDIDO_CAVALO INT FOREIGN KEY REFERENCES PEDIDO_CAVALO(ID_PEDIDO_CAVALO)
)
INSERT INTO FORNECEDOR_CAVALO  VALUES 
('FORNECEDOR CAVALO F'),('FORNECEDOR CAVALO S')
INSERT INTO CAVALO (NOME_CAVALO,ID_FORNECEDOR_CAVALO,CODIGO_CAVALO) VALUES
('CAVALO F',1,'F_CAVALO'),('CAVALO F2',1,'F2_CAVALO'),('CAVALO S',2,'S_CAVALO'),('CAVALO S2',2,'S2_CAVALO')
,('CAVALO ZY',2,'ZY_CAVALO')
INSERT INTO CLIENTE_CAVALO VALUES
('CAVALO FS INC.') , ('SSF CAVALO VENDAS SA')
INSERT INTO PEDIDO_CAVALO 
(NUMERO_PEDIDO_CAVALO,QUANTIDADE_TOTAL,VALOR_TOTAL,DATA,ID_CLIENTE_CAVALO) VALUES
(100,2,1000,'2000-01-01',1),
(150,1,500,'2000-02-01',2),
(180,1,500,'2000-03-01',2),
(190,3,1500,'2000-04-01',2)
INSERT INTO DETALHE_PEDIDO_CAVALO (ID_CAVALO,QUANTIDADE,VALOR,ID_PEDIDO_CAVALO) VALUES
(1,1,500,1),
(2,1,500,1),
(1,1,500,2),
(2,1,500,3), 
(3,1,500,4),
(4,2,1000,4)
 /*
 Ola Danilo Moraes de Lima tudo bem com você? Preciso de uma ajuda aqui para entregar um relatório. Da uma força!
1 - Poderia selecionar o nome dos CAVALOS e o nome do fornecedor dos CAVALOS 
    onde o codigo do CAVALO não  começe com S, ordenados pelo nome do CAVALO?
*/
/*
2 - Poderia selecionar o nome dos clientes a data do pedido do CAVALO, quantidade e  valor
    onde a data do pedido é maior que 2000-03-01?
*/
/*
3 - Poderia criar uma tabela chamada [COMPRAS_CAVALO] com os valores
o nome do CAVALO, o nome do cliente, data da compra ?
*/

/*
4 - Poderia criar uma consulta, para buscar o NOME dos CAVALOS que não tiveram nenhuma compra?
(PS: OBRIGATÓRIO TER UM JOIN ENTRE A TABELA CAVALO E PEDIDO_CAVALO, 
NADA DE SELECT * FROM CAVALOS where NOME = XXX não!
*/
 /*
5 - Poderia criar uma tabela chamada [COMPRAS_CAVALO_FORNECEDOR] com os valores
o nome do CAVALO, quantidade do CAVALO vendida, o valor e o nome do fornecedor onde o 
nome do fornecedor não   termine com a letra F? */