USE MASTER 
DROP DATABASE IF EXISTS RELOGIO
GO
CREATE DATABASE RELOGIO
GO
 USE RELOGIO
CREATE TABLE FORNECEDOR_RELOGIO
(
ID_FORNECEDOR_RELOGIO  INT IDENTITY(1,1) PRIMARY KEY,
NOME_FORNECEDOR VARCHAR(MAX)
)
CREATE TABLE RELOGIO
(
ID_RELOGIO INT IDENTITY(1,1) PRIMARY KEY,
NOME_RELOGIO VARCHAR(200) UNIQUE,
CODIGO_RELOGIO VARCHAR(200)  ,
ID_FORNECEDOR_RELOGIO INT FOREIGN KEY REFERENCES FORNECEDOR_RELOGIO(ID_FORNECEDOR_RELOGIO)
)
CREATE TABLE CLIENTE_RELOGIO
(
ID_CLIENTE_RELOGIO INT IDENTITY(1,1) PRIMARY KEY,
NOME_CLIENTE_RELOGIO VARCHAR(200)
)
CREATE TABLE PEDIDO_RELOGIO
(
ID_PEDIDO_RELOGIO INT IDENTITY(1,1) PRIMARY KEY,
NUMERO_PEDIDO_RELOGIO INT  ,
QUANTIDADE_TOTAL INT,
VALOR_TOTAL DECIMAL(10,2),
DATA DATE,
ID_CLIENTE_RELOGIO INT FOREIGN KEY REFERENCES CLIENTE_RELOGIO(ID_CLIENTE_RELOGIO)
)
CREATE TABLE DETALHE_PEDIDO_RELOGIO
(
ID_DETALHE_PEDIDO_RELOGIO INT IDENTITY(1,1) PRIMARY KEY,
ID_RELOGIO  INT FOREIGN KEY REFERENCES RELOGIO(ID_RELOGIO),
QUANTIDADE INT,
VALOR DECIMAL(10,2),
ID_PEDIDO_RELOGIO INT FOREIGN KEY REFERENCES PEDIDO_RELOGIO(ID_PEDIDO_RELOGIO)
)
INSERT INTO FORNECEDOR_RELOGIO  VALUES 
('FORNECEDOR RELOGIO K'),('FORNECEDOR RELOGIO N')
INSERT INTO RELOGIO (NOME_RELOGIO,ID_FORNECEDOR_RELOGIO,CODIGO_RELOGIO) VALUES
('RELOGIO K',1,'K_RELOGIO'),('RELOGIO K2',1,'K2_RELOGIO'),('RELOGIO N',2,'N_RELOGIO'),('RELOGIO N2',2,'N2_RELOGIO')
,('RELOGIO ZY',2,'ZY_RELOGIO')
INSERT INTO CLIENTE_RELOGIO VALUES
('RELOGIO KN INC.') , ('NNK RELOGIO VENDAS SA')
INSERT INTO PEDIDO_RELOGIO 
(NUMERO_PEDIDO_RELOGIO,QUANTIDADE_TOTAL,VALOR_TOTAL,DATA,ID_CLIENTE_RELOGIO) VALUES
(100,2,1000,'2000-01-01',1),
(150,1,500,'2000-02-01',2),
(180,1,500,'2000-03-01',2),
(190,3,1500,'2000-04-01',2)
INSERT INTO DETALHE_PEDIDO_RELOGIO (ID_RELOGIO,QUANTIDADE,VALOR,ID_PEDIDO_RELOGIO) VALUES
(1,1,500,1),
(2,1,500,1),
(1,1,500,2),
(2,1,500,3), 
(3,1,500,4),
(4,2,1000,4)
 /*
 Ola Hugo Lacerda Rocha tudo bem com você? Preciso de uma ajuda aqui para entregar um relatório. Da uma força!
1 - Poderia selecionar o nome dos RELOGIOS e o nome do fornecedor dos RELOGIOS 
    onde o codigo do RELOGIO    começe com N, ordenados pelo nome do RELOGIO?
*/
/*
2 - Poderia selecionar o nome dos clientes a data do pedido do RELOGIO, quantidade e  valor
    onde a data do pedido é maior que 2000-03-01?
*/
/*
3 - Poderia criar uma tabela chamada [COMPRAS_RELOGIO] com os valores
o nome do RELOGIO, o nome do cliente, data da compra ?
*/

/*
4 - Poderia criar uma consulta, para buscar o NOME dos RELOGIOS que   tiveram nenhuma compra?
(PS: OBRIGATÓRIO TER UM JOIN ENTRE A TABELA RELOGIO E PEDIDO_RELOGIO, 
NADA DE SELECT * FROM RELOGIOS where NOME = XXX não!
*/
 /*
5 - Poderia criar uma tabela chamada [COMPRAS_RELOGIO_FORNECEDOR] com os valores
o nome do RELOGIO, quantidade do RELOGIO vendida, o valor e o nome do fornecedor onde o 
nome do fornecedor     termine com a letra K? */