USE MASTER 
DROP DATABASE IF EXISTS BONECO
GO
CREATE DATABASE BONECO
GO
 USE BONECO
CREATE TABLE FORNECEDOR_BONECO
(
ID_FORNECEDOR_BONECO  INT IDENTITY(1,1) PRIMARY KEY,
NOME_FORNECEDOR VARCHAR(MAX)
)
CREATE TABLE BONECO
(
ID_BONECO INT IDENTITY(1,1) PRIMARY KEY,
NOME_BONECO VARCHAR(200) UNIQUE,
CODIGO_BONECO VARCHAR(200)  ,
ID_FORNECEDOR_BONECO INT FOREIGN KEY REFERENCES FORNECEDOR_BONECO(ID_FORNECEDOR_BONECO)
)
CREATE TABLE CLIENTE_BONECO
(
ID_CLIENTE_BONECO INT IDENTITY(1,1) PRIMARY KEY,
NOME_CLIENTE_BONECO VARCHAR(200)
)
CREATE TABLE PEDIDO_BONECO
(
ID_PEDIDO_BONECO INT IDENTITY(1,1) PRIMARY KEY,
NUMERO_PEDIDO_BONECO INT  ,
QUANTIDADE_TOTAL INT,
VALOR_TOTAL DECIMAL(10,2),
DATA DATE,
ID_CLIENTE_BONECO INT FOREIGN KEY REFERENCES CLIENTE_BONECO(ID_CLIENTE_BONECO)
)
CREATE TABLE DETALHE_PEDIDO_BONECO
(
ID_DETALHE_PEDIDO_BONECO INT IDENTITY(1,1) PRIMARY KEY,
ID_BONECO  INT FOREIGN KEY REFERENCES BONECO(ID_BONECO),
QUANTIDADE INT,
VALOR DECIMAL(10,2),
ID_PEDIDO_BONECO INT FOREIGN KEY REFERENCES PEDIDO_BONECO(ID_PEDIDO_BONECO)
)
INSERT INTO FORNECEDOR_BONECO  VALUES 
('FORNECEDOR BONECO Y'),('FORNECEDOR BONECO j')
INSERT INTO BONECO (NOME_BONECO,ID_FORNECEDOR_BONECO,CODIGO_BONECO) VALUES
('BONECO Y',1,'Y_BONECO'),('BONECO Y2',1,'Y2_BONECO'),('BONECO j',2,'j_BONECO'),('BONECO j2',2,'j2_BONECO')
,('BONECO ZY',2,'ZY_BONECO')
INSERT INTO CLIENTE_BONECO VALUES
('BONECO Yj INC.') , ('jjY BONECO VENDAS SA')
INSERT INTO PEDIDO_BONECO 
(NUMERO_PEDIDO_BONECO,QUANTIDADE_TOTAL,VALOR_TOTAL,DATA,ID_CLIENTE_BONECO) VALUES
(100,2,1000,'2000-01-01',1),
(150,1,500,'2000-02-01',2),
(180,1,500,'2000-03-01',2),
(190,3,1500,'2000-04-01',2)
INSERT INTO DETALHE_PEDIDO_BONECO (ID_BONECO,QUANTIDADE,VALOR,ID_PEDIDO_BONECO) VALUES
(1,1,500,1),
(2,1,500,1),
(1,1,500,2),
(2,1,500,3), 
(3,1,500,4),
(4,2,1000,4)
 /*
 Ola Patricia Silva de Oliveira tudo bem com você? Preciso de uma ajuda aqui para entregar um relatório. Da uma força!
1 - Poderia selecionar o nome dos BONECOS e o nome do fornecedor dos BONECOS 
    onde o codigo do BONECO    começe com j, ordenados pelo nome do BONECO?
*/
/*
2 - Poderia selecionar o nome dos clientes a data do pedido do BONECO, quantidade e  valor
    onde a data do pedido é maior que 2000-03-01?
*/
/*
3 - Poderia criar uma tabela chamada [COMPRAS_BONECO] com os valores
o nome do BONECO, o nome do cliente, data da compra ?
*/

/*
4 - Poderia criar uma consulta, para buscar o NOME dos BONECOS que   tiveram nenhuma compra?
(PS: OBRIGATÓRIO TER UM JOIN ENTRE A TABELA BONECO E PEDIDO_BONECO, 
NADA DE SELECT * FROM BONECOS where NOME = XXX não!
*/
 /*
5 - Poderia criar uma tabela chamada [COMPRAS_BONECO_FORNECEDOR] com os valores
o nome do BONECO, quantidade do BONECO vendida, o valor e o nome do fornecedor onde o 
nome do fornecedor     termine com a letra Y? */