USE MASTER 
DROP DATABASE IF EXISTS JATO
GO
CREATE DATABASE JATO
GO
 USE JATO
CREATE TABLE FORNECEDOR_JATO
(
ID_FORNECEDOR_JATO  INT IDENTITY(1,1) PRIMARY KEY,
NOME_FORNECEDOR VARCHAR(MAX)
)
CREATE TABLE JATO
(
ID_JATO INT IDENTITY(1,1) PRIMARY KEY,
NOME_JATO VARCHAR(200) UNIQUE,
CODIGO_JATO VARCHAR(200)  ,
ID_FORNECEDOR_JATO INT FOREIGN KEY REFERENCES FORNECEDOR_JATO(ID_FORNECEDOR_JATO)
)
CREATE TABLE CLIENTE_JATO
(
ID_CLIENTE_JATO INT IDENTITY(1,1) PRIMARY KEY,
NOME_CLIENTE_JATO VARCHAR(200)
)
CREATE TABLE PEDIDO_JATO
(
ID_PEDIDO_JATO INT IDENTITY(1,1) PRIMARY KEY,
NUMERO_PEDIDO_JATO INT  ,
QUANTIDADE_TOTAL INT,
VALOR_TOTAL DECIMAL(10,2),
DATA DATE,
ID_CLIENTE_JATO INT FOREIGN KEY REFERENCES CLIENTE_JATO(ID_CLIENTE_JATO)
)
CREATE TABLE DETALHE_PEDIDO_JATO
(
ID_DETALHE_PEDIDO_JATO INT IDENTITY(1,1) PRIMARY KEY,
ID_JATO  INT FOREIGN KEY REFERENCES JATO(ID_JATO),
QUANTIDADE INT,
VALOR DECIMAL(10,2),
ID_PEDIDO_JATO INT FOREIGN KEY REFERENCES PEDIDO_JATO(ID_PEDIDO_JATO)
)
INSERT INTO FORNECEDOR_JATO  VALUES 
('FORNECEDOR JATO S'),('FORNECEDOR JATO F')
INSERT INTO JATO (NOME_JATO,ID_FORNECEDOR_JATO,CODIGO_JATO) VALUES
('JATO S',1,'S_JATO'),('JATO S2',1,'S2_JATO'),('JATO F',2,'F_JATO'),('JATO F2',2,'F2_JATO')
,('JATO ZY',2,'ZY_JATO')
INSERT INTO CLIENTE_JATO VALUES
('JATO SF INC.') , ('FFS JATO VENDAS SA')
INSERT INTO PEDIDO_JATO 
(NUMERO_PEDIDO_JATO,QUANTIDADE_TOTAL,VALOR_TOTAL,DATA,ID_CLIENTE_JATO) VALUES
(100,2,1000,'2000-01-01',1),
(150,1,500,'2000-02-01',2),
(180,1,500,'2000-03-01',2),
(190,3,1500,'2000-04-01',2)
INSERT INTO DETALHE_PEDIDO_JATO (ID_JATO,QUANTIDADE,VALOR,ID_PEDIDO_JATO) VALUES
(1,1,500,1),
(2,1,500,1),
(1,1,500,2),
(2,1,500,3), 
(3,1,500,4),
(4,2,1000,4)
 /*
 Ola Marcos Mauricio Daninger tudo bem com você? Preciso de uma ajuda aqui para entregar um relatório. Da uma força!
1 - Poderia selecionar o nome dos JATOS e o nome do fornecedor dos JATOS 
    onde o codigo do JATO    começe com F, ordenados pelo nome do JATO?
*/
/*
2 - Poderia selecionar o nome dos clientes a data do pedido do JATO, quantidade e  valor
    onde a data do pedido é maior que 2000-03-01?
*/
/*
3 - Poderia criar uma tabela chamada [COMPRAS_JATO] com os valores
o nome do JATO, o nome do cliente, data da compra ?
*/

/*
4 - Poderia criar uma consulta, para buscar o NOME dos JATOS que   tiveram nenhuma compra?
(PS: OBRIGATÓRIO TER UM JOIN ENTRE A TABELA JATO E PEDIDO_JATO, 
NADA DE SELECT * FROM JATOS where NOME = XXX não!
*/
 /*
5 - Poderia criar uma tabela chamada [COMPRAS_JATO_FORNECEDOR] com os valores
o nome do JATO, quantidade do JATO vendida, o valor e o nome do fornecedor onde o 
nome do fornecedor     termine com a letra S? */