USE MASTER 
DROP DATABASE IF EXISTS CANHAO
GO
CREATE DATABASE CANHAO
GO
 USE CANHAO
CREATE TABLE FORNECEDOR_CANHAO
(
ID_FORNECEDOR_CANHAO  INT IDENTITY(1,1) PRIMARY KEY,
NOME_FORNECEDOR VARCHAR(MAX)
)
CREATE TABLE CANHAO
(
ID_CANHAO INT IDENTITY(1,1) PRIMARY KEY,
NOME_CANHAO VARCHAR(200) UNIQUE,
CODIGO_CANHAO VARCHAR(200)  ,
ID_FORNECEDOR_CANHAO INT FOREIGN KEY REFERENCES FORNECEDOR_CANHAO(ID_FORNECEDOR_CANHAO)
)
CREATE TABLE CLIENTE_CANHAO
(
ID_CLIENTE_CANHAO INT IDENTITY(1,1) PRIMARY KEY,
NOME_CLIENTE_CANHAO VARCHAR(200)
)
CREATE TABLE PEDIDO_CANHAO
(
ID_PEDIDO_CANHAO INT IDENTITY(1,1) PRIMARY KEY,
NUMERO_PEDIDO_CANHAO INT  ,
QUANTIDADE_TOTAL INT,
VALOR_TOTAL DECIMAL(10,2),
DATA DATE,
ID_CLIENTE_CANHAO INT FOREIGN KEY REFERENCES CLIENTE_CANHAO(ID_CLIENTE_CANHAO)
)
CREATE TABLE DETALHE_PEDIDO_CANHAO
(
ID_DETALHE_PEDIDO_CANHAO INT IDENTITY(1,1) PRIMARY KEY,
ID_CANHAO  INT FOREIGN KEY REFERENCES CANHAO(ID_CANHAO),
QUANTIDADE INT,
VALOR DECIMAL(10,2),
ID_PEDIDO_CANHAO INT FOREIGN KEY REFERENCES PEDIDO_CANHAO(ID_PEDIDO_CANHAO)
)
INSERT INTO FORNECEDOR_CANHAO  VALUES 
('FORNECEDOR CANHAO I'),('FORNECEDOR CANHAO P')
INSERT INTO CANHAO (NOME_CANHAO,ID_FORNECEDOR_CANHAO,CODIGO_CANHAO) VALUES
('CANHAO I',1,'I_CANHAO'),('CANHAO I2',1,'I2_CANHAO'),('CANHAO P',2,'P_CANHAO'),('CANHAO P2',2,'P2_CANHAO')
,('CANHAO ZY',2,'ZY_CANHAO')
INSERT INTO CLIENTE_CANHAO VALUES
('CANHAO IP INC.') , ('PPI CANHAO VENDAS SA')
INSERT INTO PEDIDO_CANHAO 
(NUMERO_PEDIDO_CANHAO,QUANTIDADE_TOTAL,VALOR_TOTAL,DATA,ID_CLIENTE_CANHAO) VALUES
(100,2,1000,'2000-01-01',1),
(150,1,500,'2000-02-01',2),
(180,1,500,'2000-03-01',2),
(190,3,1500,'2000-04-01',2)
INSERT INTO DETALHE_PEDIDO_CANHAO (ID_CANHAO,QUANTIDADE,VALOR,ID_PEDIDO_CANHAO) VALUES
(1,1,500,1),
(2,1,500,1),
(1,1,500,2),
(2,1,500,3), 
(3,1,500,4),
(4,2,1000,4)
 /*
 Ola Felipe Silva Leite tudo bem com você? Preciso de uma ajuda aqui para entregar um relatório. Da uma força!
1 - Poderia selecionar o nome dos CANHAOS e o nome do fornecedor dos CANHAOS 
    onde o codigo do CANHAO    começe com P, ordenados pelo nome do CANHAO?
*/
/*
2 - Poderia selecionar o nome dos clientes a data do pedido do CANHAO, quantidade e  valor
    onde a data do pedido é maior que 2000-03-01?
*/
/*
3 - Poderia criar uma tabela chamada [COMPRAS_CANHAO] com os valores
o nome do CANHAO, o nome do cliente, data da compra ?
*/

/*
4 - Poderia criar uma consulta, para buscar o NOME dos CANHAOS que   tiveram nenhuma compra?
(PS: OBRIGATÓRIO TER UM JOIN ENTRE A TABELA CANHAO E PEDIDO_CANHAO, 
NADA DE SELECT * FROM CANHAOS where NOME = XXX não!
*/
 /*
5 - Poderia criar uma tabela chamada [COMPRAS_CANHAO_FORNECEDOR] com os valores
o nome do CANHAO, quantidade do CANHAO vendida, o valor e o nome do fornecedor onde o 
nome do fornecedor     termine com a letra I? */