USE MASTER 
DROP DATABASE IF EXISTS IMOVEL
GO
CREATE DATABASE IMOVEL
GO
 USE IMOVEL
CREATE TABLE FORNECEDOR_IMOVEL
(
ID_FORNECEDOR_IMOVEL  INT IDENTITY(1,1) PRIMARY KEY,
NOME_FORNECEDOR VARCHAR(MAX)
)
CREATE TABLE IMOVEL
(
ID_IMOVEL INT IDENTITY(1,1) PRIMARY KEY,
NOME_IMOVEL VARCHAR(200) UNIQUE,
CODIGO_IMOVEL VARCHAR(200)  ,
ID_FORNECEDOR_IMOVEL INT FOREIGN KEY REFERENCES FORNECEDOR_IMOVEL(ID_FORNECEDOR_IMOVEL)
)
CREATE TABLE CLIENTE_IMOVEL
(
ID_CLIENTE_IMOVEL INT IDENTITY(1,1) PRIMARY KEY,
NOME_CLIENTE_IMOVEL VARCHAR(200)
)
CREATE TABLE PEDIDO_IMOVEL
(
ID_PEDIDO_IMOVEL INT IDENTITY(1,1) PRIMARY KEY,
NUMERO_PEDIDO_IMOVEL INT  ,
QUANTIDADE_TOTAL INT,
VALOR_TOTAL DECIMAL(10,2),
DATA DATE,
ID_CLIENTE_IMOVEL INT FOREIGN KEY REFERENCES CLIENTE_IMOVEL(ID_CLIENTE_IMOVEL)
)
CREATE TABLE DETALHE_PEDIDO_IMOVEL
(
ID_DETALHE_PEDIDO_IMOVEL INT IDENTITY(1,1) PRIMARY KEY,
ID_IMOVEL  INT FOREIGN KEY REFERENCES IMOVEL(ID_IMOVEL),
QUANTIDADE INT,
VALOR DECIMAL(10,2),
ID_PEDIDO_IMOVEL INT FOREIGN KEY REFERENCES PEDIDO_IMOVEL(ID_PEDIDO_IMOVEL)
)
INSERT INTO FORNECEDOR_IMOVEL  VALUES 
('FORNECEDOR IMOVEL E'),('FORNECEDOR IMOVEL T')
INSERT INTO IMOVEL (NOME_IMOVEL,ID_FORNECEDOR_IMOVEL,CODIGO_IMOVEL) VALUES
('IMOVEL E',1,'E_IMOVEL'),('IMOVEL E2',1,'E2_IMOVEL'),('IMOVEL T',2,'T_IMOVEL'),('IMOVEL T2',2,'T2_IMOVEL')
,('IMOVEL ZY',2,'ZY_IMOVEL')
INSERT INTO CLIENTE_IMOVEL VALUES
('IMOVEL ET INC.') , ('TTE IMOVEL VENDAS SA')
INSERT INTO PEDIDO_IMOVEL 
(NUMERO_PEDIDO_IMOVEL,QUANTIDADE_TOTAL,VALOR_TOTAL,DATA,ID_CLIENTE_IMOVEL) VALUES
(100,2,1000,'2000-01-01',1),
(150,1,500,'2000-02-01',2),
(180,1,500,'2000-03-01',2),
(190,3,1500,'2000-04-01',2)
INSERT INTO DETALHE_PEDIDO_IMOVEL (ID_IMOVEL,QUANTIDADE,VALOR,ID_PEDIDO_IMOVEL) VALUES
(1,1,500,1),
(2,1,500,1),
(1,1,500,2),
(2,1,500,3), 
(3,1,500,4),
(4,2,1000,4)
 /*
 Ola Vitor Pires Ferreira Leite tudo bem com você? Preciso de uma ajuda aqui para entregar um relatório. Da uma força!
1 - Poderia selecionar o nome dos IMOVELS e o nome do fornecedor dos IMOVELS 
    onde o codigo do IMOVEL não  começe com T, ordenados pelo nome do IMOVEL?
*/
/*
2 - Poderia selecionar o nome dos clientes a data do pedido do IMOVEL, quantidade e  valor
    onde a data do pedido é maior que 2000-03-01?
*/
/*
3 - Poderia criar uma tabela chamada [COMPRAS_IMOVEL] com os valores
o nome do IMOVEL, o nome do cliente, data da compra ?
*/

/*
4 - Poderia criar uma consulta, para buscar o NOME dos IMOVELS que não tiveram nenhuma compra?
(PS: OBRIGATÓRIO TER UM JOIN ENTRE A TABELA IMOVEL E PEDIDO_IMOVEL, 
NADA DE SELECT * FROM IMOVELS where NOME = XXX não!
*/
 /*
5 - Poderia criar uma tabela chamada [COMPRAS_IMOVEL_FORNECEDOR] com os valores
o nome do IMOVEL, quantidade do IMOVEL vendida, o valor e o nome do fornecedor onde o 
nome do fornecedor não   termine com a letra E? */