USE MASTER 
DROP DATABASE IF EXISTS GALO
GO
CREATE DATABASE GALO
GO
 USE GALO
CREATE TABLE FORNECEDOR_GALO
(
ID_FORNECEDOR_GALO  INT IDENTITY(1,1) PRIMARY KEY,
NOME_FORNECEDOR VARCHAR(MAX)
)
CREATE TABLE GALO
(
ID_GALO INT IDENTITY(1,1) PRIMARY KEY,
NOME_GALO VARCHAR(200) UNIQUE,
CODIGO_GALO VARCHAR(200)  ,
ID_FORNECEDOR_GALO INT FOREIGN KEY REFERENCES FORNECEDOR_GALO(ID_FORNECEDOR_GALO)
)
CREATE TABLE CLIENTE_GALO
(
ID_CLIENTE_GALO INT IDENTITY(1,1) PRIMARY KEY,
NOME_CLIENTE_GALO VARCHAR(200)
)
CREATE TABLE PEDIDO_GALO
(
ID_PEDIDO_GALO INT IDENTITY(1,1) PRIMARY KEY,
NUMERO_PEDIDO_GALO INT  ,
QUANTIDADE_TOTAL INT,
VALOR_TOTAL DECIMAL(10,2),
DATA DATE,
ID_CLIENTE_GALO INT FOREIGN KEY REFERENCES CLIENTE_GALO(ID_CLIENTE_GALO)
)
CREATE TABLE DETALHE_PEDIDO_GALO
(
ID_DETALHE_PEDIDO_GALO INT IDENTITY(1,1) PRIMARY KEY,
ID_GALO  INT FOREIGN KEY REFERENCES GALO(ID_GALO),
QUANTIDADE INT,
VALOR DECIMAL(10,2),
ID_PEDIDO_GALO INT FOREIGN KEY REFERENCES PEDIDO_GALO(ID_PEDIDO_GALO)
)
INSERT INTO FORNECEDOR_GALO  VALUES 
('FORNECEDOR GALO P'),('FORNECEDOR GALO I')
INSERT INTO GALO (NOME_GALO,ID_FORNECEDOR_GALO,CODIGO_GALO) VALUES
('GALO P',1,'P_GALO'),('GALO P2',1,'P2_GALO'),('GALO I',2,'I_GALO'),('GALO I2',2,'I2_GALO')
,('GALO ZY',2,'ZY_GALO')
INSERT INTO CLIENTE_GALO VALUES
('GALO PI INC.') , ('IIP GALO VENDAS SA')
INSERT INTO PEDIDO_GALO 
(NUMERO_PEDIDO_GALO,QUANTIDADE_TOTAL,VALOR_TOTAL,DATA,ID_CLIENTE_GALO) VALUES
(100,2,1000,'2000-01-01',1),
(150,1,500,'2000-02-01',2),
(180,1,500,'2000-03-01',2),
(190,3,1500,'2000-04-01',2)
INSERT INTO DETALHE_PEDIDO_GALO (ID_GALO,QUANTIDADE,VALOR,ID_PEDIDO_GALO) VALUES
(1,1,500,1),
(2,1,500,1),
(1,1,500,2),
(2,1,500,3), 
(3,1,500,4),
(4,2,1000,4)
 /*
 Ola Lucas Aragão do Amaral tudo bem com você? Preciso de uma ajuda aqui para entregar um relatório. Da uma força!
1 - Poderia selecionar o nome dos GALOS e o nome do fornecedor dos GALOS 
    onde o codigo do GALO não  começe com I, ordenados pelo nome do GALO?
*/
/*
2 - Poderia selecionar o nome dos clientes a data do pedido do GALO, quantidade e  valor
    onde a data do pedido é maior que 2000-03-01?
*/
/*
3 - Poderia criar uma tabela chamada [COMPRAS_GALO] com os valores
o nome do GALO, o nome do cliente, data da compra ?
*/

/*
4 - Poderia criar uma consulta, para buscar o NOME dos GALOS que não tiveram nenhuma compra?
(PS: OBRIGATÓRIO TER UM JOIN ENTRE A TABELA GALO E PEDIDO_GALO, 
NADA DE SELECT * FROM GALOS where NOME = XXX não!
*/
 /*
5 - Poderia criar uma tabela chamada [COMPRAS_GALO_FORNECEDOR] com os valores
o nome do GALO, quantidade do GALO vendida, o valor e o nome do fornecedor onde o 
nome do fornecedor não   termine com a letra P? */