USE MASTER 
DROP DATABASE IF EXISTS GUARDANAPO
GO
CREATE DATABASE GUARDANAPO
GO
 USE GUARDANAPO
CREATE TABLE FORNECEDOR_GUARDANAPO
(
ID_FORNECEDOR_GUARDANAPO  INT IDENTITY(1,1) PRIMARY KEY,
NOME_FORNECEDOR VARCHAR(MAX)
)
CREATE TABLE GUARDANAPO
(
ID_GUARDANAPO INT IDENTITY(1,1) PRIMARY KEY,
NOME_GUARDANAPO VARCHAR(200) UNIQUE,
CODIGO_GUARDANAPO VARCHAR(200)  ,
ID_FORNECEDOR_GUARDANAPO INT FOREIGN KEY REFERENCES FORNECEDOR_GUARDANAPO(ID_FORNECEDOR_GUARDANAPO)
)
CREATE TABLE CLIENTE_GUARDANAPO
(
ID_CLIENTE_GUARDANAPO INT IDENTITY(1,1) PRIMARY KEY,
NOME_CLIENTE_GUARDANAPO VARCHAR(200)
)
CREATE TABLE PEDIDO_GUARDANAPO
(
ID_PEDIDO_GUARDANAPO INT IDENTITY(1,1) PRIMARY KEY,
NUMERO_PEDIDO_GUARDANAPO INT  ,
QUANTIDADE_TOTAL INT,
VALOR_TOTAL DECIMAL(10,2),
DATA DATE,
ID_CLIENTE_GUARDANAPO INT FOREIGN KEY REFERENCES CLIENTE_GUARDANAPO(ID_CLIENTE_GUARDANAPO)
)
CREATE TABLE DETALHE_PEDIDO_GUARDANAPO
(
ID_DETALHE_PEDIDO_GUARDANAPO INT IDENTITY(1,1) PRIMARY KEY,
ID_GUARDANAPO  INT FOREIGN KEY REFERENCES GUARDANAPO(ID_GUARDANAPO),
QUANTIDADE INT,
VALOR DECIMAL(10,2),
ID_PEDIDO_GUARDANAPO INT FOREIGN KEY REFERENCES PEDIDO_GUARDANAPO(ID_PEDIDO_GUARDANAPO)
)
INSERT INTO FORNECEDOR_GUARDANAPO  VALUES 
('FORNECEDOR GUARDANAPO W'),('FORNECEDOR GUARDANAPO B')
INSERT INTO GUARDANAPO (NOME_GUARDANAPO,ID_FORNECEDOR_GUARDANAPO,CODIGO_GUARDANAPO) VALUES
('GUARDANAPO W',1,'W_GUARDANAPO'),('GUARDANAPO W2',1,'W2_GUARDANAPO'),('GUARDANAPO B',2,'B_GUARDANAPO'),('GUARDANAPO B2',2,'B2_GUARDANAPO')
,('GUARDANAPO ZY',2,'ZY_GUARDANAPO')
INSERT INTO CLIENTE_GUARDANAPO VALUES
('GUARDANAPO WB INC.') , ('BBW GUARDANAPO VENDAS SA')
INSERT INTO PEDIDO_GUARDANAPO 
(NUMERO_PEDIDO_GUARDANAPO,QUANTIDADE_TOTAL,VALOR_TOTAL,DATA,ID_CLIENTE_GUARDANAPO) VALUES
(100,2,1000,'2000-01-01',1),
(150,1,500,'2000-02-01',2),
(180,1,500,'2000-03-01',2),
(190,3,1500,'2000-04-01',2)
INSERT INTO DETALHE_PEDIDO_GUARDANAPO (ID_GUARDANAPO,QUANTIDADE,VALOR,ID_PEDIDO_GUARDANAPO) VALUES
(1,1,500,1),
(2,1,500,1),
(1,1,500,2),
(2,1,500,3), 
(3,1,500,4),
(4,2,1000,4)
 /*
 Ola Micael de Jesus Santos tudo bem com você? Preciso de uma ajuda aqui para entregar um relatório. Da uma força!
1 - Poderia selecionar o nome dos GUARDANAPOS e o nome do fornecedor dos GUARDANAPOS 
    onde o codigo do GUARDANAPO    começe com B, ordenados pelo nome do GUARDANAPO?
*/
/*
2 - Poderia selecionar o nome dos clientes a data do pedido do GUARDANAPO, quantidade e  valor
    onde a data do pedido é maior que 2000-03-01?
*/
/*
3 - Poderia criar uma tabela chamada [COMPRAS_GUARDANAPO] com os valores
o nome do GUARDANAPO, o nome do cliente, data da compra ?
*/

/*
4 - Poderia criar uma consulta, para buscar o NOME dos GUARDANAPOS que   tiveram nenhuma compra?
(PS: OBRIGATÓRIO TER UM JOIN ENTRE A TABELA GUARDANAPO E PEDIDO_GUARDANAPO, 
NADA DE SELECT * FROM GUARDANAPOS where NOME = XXX não!
*/
 /*
5 - Poderia criar uma tabela chamada [COMPRAS_GUARDANAPO_FORNECEDOR] com os valores
o nome do GUARDANAPO, quantidade do GUARDANAPO vendida, o valor e o nome do fornecedor onde o 
nome do fornecedor     termine com a letra W? */