USE MASTER 
DROP DATABASE IF EXISTS MUNICAO
GO
CREATE DATABASE MUNICAO
GO
 USE MUNICAO
CREATE TABLE FORNECEDOR_MUNICAO
(
ID_FORNECEDOR_MUNICAO  INT IDENTITY(1,1) PRIMARY KEY,
NOME_FORNECEDOR VARCHAR(MAX)
)
CREATE TABLE MUNICAO
(
ID_MUNICAO INT IDENTITY(1,1) PRIMARY KEY,
NOME_MUNICAO VARCHAR(200) UNIQUE,
CODIGO_MUNICAO VARCHAR(200)  ,
ID_FORNECEDOR_MUNICAO INT FOREIGN KEY REFERENCES FORNECEDOR_MUNICAO(ID_FORNECEDOR_MUNICAO)
)
CREATE TABLE CLIENTE_MUNICAO
(
ID_CLIENTE_MUNICAO INT IDENTITY(1,1) PRIMARY KEY,
NOME_CLIENTE_MUNICAO VARCHAR(200)
)
CREATE TABLE PEDIDO_MUNICAO
(
ID_PEDIDO_MUNICAO INT IDENTITY(1,1) PRIMARY KEY,
NUMERO_PEDIDO_MUNICAO INT  ,
QUANTIDADE_TOTAL INT,
VALOR_TOTAL DECIMAL(10,2),
DATA DATE,
ID_CLIENTE_MUNICAO INT FOREIGN KEY REFERENCES CLIENTE_MUNICAO(ID_CLIENTE_MUNICAO)
)
CREATE TABLE DETALHE_PEDIDO_MUNICAO
(
ID_DETALHE_PEDIDO_MUNICAO INT IDENTITY(1,1) PRIMARY KEY,
ID_MUNICAO  INT FOREIGN KEY REFERENCES MUNICAO(ID_MUNICAO),
QUANTIDADE INT,
VALOR DECIMAL(10,2),
ID_PEDIDO_MUNICAO INT FOREIGN KEY REFERENCES PEDIDO_MUNICAO(ID_PEDIDO_MUNICAO)
)
INSERT INTO FORNECEDOR_MUNICAO  VALUES 
('FORNECEDOR MUNICAO D'),('FORNECEDOR MUNICAO U')
INSERT INTO MUNICAO (NOME_MUNICAO,ID_FORNECEDOR_MUNICAO,CODIGO_MUNICAO) VALUES
('MUNICAO D',1,'D_MUNICAO'),('MUNICAO D2',1,'D2_MUNICAO'),('MUNICAO U',2,'U_MUNICAO'),('MUNICAO U2',2,'U2_MUNICAO')
,('MUNICAO ZY',2,'ZY_MUNICAO')
INSERT INTO CLIENTE_MUNICAO VALUES
('MUNICAO DU INC.') , ('UUD MUNICAO VENDAS SA')
INSERT INTO PEDIDO_MUNICAO 
(NUMERO_PEDIDO_MUNICAO,QUANTIDADE_TOTAL,VALOR_TOTAL,DATA,ID_CLIENTE_MUNICAO) VALUES
(100,2,1000,'2000-01-01',1),
(150,1,500,'2000-02-01',2),
(180,1,500,'2000-03-01',2),
(190,3,1500,'2000-04-01',2)
INSERT INTO DETALHE_PEDIDO_MUNICAO (ID_MUNICAO,QUANTIDADE,VALOR,ID_PEDIDO_MUNICAO) VALUES
(1,1,500,1),
(2,1,500,1),
(1,1,500,2),
(2,1,500,3), 
(3,1,500,4),
(4,2,1000,4)
 /*
 Ola Rodrigo da Silva Rodrigues tudo bem com você? Preciso de uma ajuda aqui para entregar um relatório. Da uma força!
1 - Poderia selecionar o nome dos MUNICAOS e o nome do fornecedor dos MUNICAOS 
    onde o codigo do MUNICAO    começe com U, ordenados pelo nome do MUNICAO?
*/
/*
2 - Poderia selecionar o nome dos clientes a data do pedido do MUNICAO, quantidade e  valor
    onde a data do pedido é maior que 2000-03-01?
*/
/*
3 - Poderia criar uma tabela chamada [COMPRAS_MUNICAO] com os valores
o nome do MUNICAO, o nome do cliente, data da compra ?
*/

/*
4 - Poderia criar uma consulta, para buscar o NOME dos MUNICAOS que   tiveram nenhuma compra?
(PS: OBRIGATÓRIO TER UM JOIN ENTRE A TABELA MUNICAO E PEDIDO_MUNICAO, 
NADA DE SELECT * FROM MUNICAOS where NOME = XXX não!
*/
 /*
5 - Poderia criar uma tabela chamada [COMPRAS_MUNICAO_FORNECEDOR] com os valores
o nome do MUNICAO, quantidade do MUNICAO vendida, o valor e o nome do fornecedor onde o 
nome do fornecedor     termine com a letra D? */