# -*- coding: utf-8 -*-
"""Exemplo1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sZKpJ0FxuNYzvrr82NoQJSqqX-ge76Jz
"""

import matplotlib.pyplot as plt

m=["Jan","Fev","Mar","Abr","Mai","Jun"]
m2 = [1,2,3,4,5,6]
m3 = [1.4,2.4,3.4,4.4,5.4,6.4]

v1=[11.2,10.11,12.08,10.2,12.91,11.1]
v2=[18.9,17.2,19,16.98,17.8,18]

#Grafico de linha
#plt.title("Dados da Loja")
#plt.xlabel("Meses")
#plt.ylabel("(em 1000 reais)")
#plt.ylim(0,30)
#plt.plot(m,v2,color = "green")
#plt.plot(m,v1)
#plt.legend(["custo","receita"])

#Grafico de barra
#plt.bar(m,v1)
#-------
#lt.bar(m2,v1,color = "red", width=0.25)
#plt.bar(m3,v2, color = "blue",width=0.25)
#plt.xticks([1.2,2.2,3.2,4.2,5.2,6.2],m)
#plt.ylim(0,30)

#Grafico de pizza
plt.pie(v1,labels=m,autopct="%.1f%%")

#