/*
AC01- CLAUSULAS SELECT E CREATE 

Turma: BD 2C
Grupo:
	Gabriel Scalione	RA: 1903812
	Isaque Ribeiro		RA: 1903978 
	Lucimara Mendes		RA: 1903617
	Mayra Fernanda		RA: 1903486
	Yuri Placido		RA: 1904177

*/

----------------------------------------------------------
-- Exercício 2 - Criação das Tabelas com base no Diagrama
----------------------------------------------------------
CREATE TABLE ESTADO (
	  ID_ESTADO INT NOT NULL IDENTITY(1,1)
	, ESTADO VARCHAR (100) NOT NULL
	, SIGLA CHAR(2) NOT NULL
	, CONSTRAINT pkESTADO PRIMARY KEY (ID_ESTADO)
)

CREATE TABLE CIDADE (
      ID_CIDADE INT NOT NULL IDENTITY(1,1)
	, CIDADE VARCHAR(100) NOT NULL
	, ID_ESTADO INT NOT NULL
	, CONSTRAINT pkCIDADE PRIMARY KEY (ID_CIDADE)
    , CONSTRAINT fkESTADO FOREIGN KEY (ID_ESTADO) REFERENCES ESTADO (ID_ESTADO)
)

CREATE TABLE ENDERECO (
      ID_ENDERECO INT NOT NULL IDENTITY(1,1)
	, LOGRADOURO VARCHAR(200)
	, NUMERO INT
	, CEP VARCHAR(9)
	, ID_CIDADE INT NOT NULL
	, CONSTRAINT pkENDERECO PRIMARY KEY (ID_ENDERECO)
    , CONSTRAINT fkCIDADE FOREIGN KEY (ID_CIDADE) REFERENCES CIDADE (ID_CIDADE)
)

CREATE TABLE CLIENTE (
      ID_CLIENTE INT NOT NULL IDENTITY(1,1)
	, CNPJ_CPF INT NOT NULL
	, NOME VARCHAR(200)
	, NOME_FANTASIA VARCHAR(200)
	, DATA_CADASTRO DATETIME
	, ID_ENDERECO INT NOT NULL
	, DATA_NASCIMENTO DATETIME
	, CONSTRAINT pkCLIENTE PRIMARY KEY (ID_CLIENTE)
	, CONSTRAINT fkENDERECO FOREIGN KEY (ID_ENDERECO) REFERENCES ENDERECO (ID_ENDERECO)
)

CREATE TABLE PEDIDO (
      ID_PEDIDO INT NOT NULL IDENTITY(1,1)
	, CONTRATO VARCHAR(100)
	, VALOR DECIMAL(10,2)
	, QUANTIDADE NUMERIC
	, DATA_PEDIDO DATETIME
	, ID_CLIENTE INT NOT NULL
	, VALOR_TOTAL DECIMAL(10,2)
	, QUANTIDADE_TOTAL NUMERIC
	, CONSTRAINT pkPEDIDO PRIMARY KEY (ID_PEDIDO)
	, CONSTRAINT fkCLIENTE FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE (ID_CLIENTE)
)

CREATE TABLE MAQUINA (
      ID_MAQUINA INT NOT NULL IDENTITY(1,1)
	, CODIGO INT NOT NULL
	, NOME VARCHAR(100)
	, DESCRICAO VARCHAR(200)
	, CONSTRAINT pkMAQUINA PRIMARY KEY (ID_MAQUINA)
)

CREATE TABLE ITEM_PEDIDO (
      ID_ITEM_PEDIDO INT NOT NULL IDENTITY(1,1)
	, ID_MAQUINA INT NOT NULL
    , ID_PEDIDO INT NOT NULL
	, QUANTIDADE NUMERIC NOT NULL
	, VALOR_TOTAL DECIMAL(10,2) NOT NULL
	, CONSTRAINT pkITEM_PEDIDO PRIMARY KEY (ID_ITEM_PEDIDO) 
	, CONSTRAINT fkMAQUINA FOREIGN KEY (ID_MAQUINA) REFERENCES MAQUINA (ID_MAQUINA)
    , CONSTRAINT fkPEDIDO FOREIGN KEY (ID_PEDIDO) REFERENCES PEDIDO (ID_PEDIDO)
)